### ISSUE TITLE
Regional breakdowns like variables

### ISSUE THREAD

**Issue by znicholls** [IAMconsortium/pyam#106]
Something that occured to me during #88 and that might be a good future enhancement.

At the moment, if you have a dataframe with regions China, Japan, Germany, UK, Europe, Asia, World, it is not clear which regions are subsets of which other regions. Hence it's impossible to automate checking of regions over all combinations (i.e. countries should add to continents, continents to World). 

If you had regions stored like variables (e.g. `World|Europe|UK`, `World`, `World|Asia`, `World|Asia|China`), then you could use the same aggregate checking logic etc. on regional breakdowns as variables.

**Comment by znicholls** [comment]
Thinking about this more, I'm not sure it's easy to cover all the possible cases. For example, if your file had regions 'world, northern hemisphere, Southern Hemisphere, r5asia, r5lam, r5maf, r5oecd, r5reg', the hierarchy wouldnt work as you do have to know how much of eg 'r5lam' goes in northern hemisphere and how much in Southern Hemisphere to do the checks. Hmm...

**Comment by danielhuppmann** [comment]
The approach we followed in (for example) the openENTRANCE [nomenclature](https://github.com/openENTRANCE/nomenclature) is to provide the region hierarchy as dictionaries and it is up to the user to use the relevant functions (like `aggregate_region()`) accordingly.
