### ISSUE TITLE
`set_meta` should require a column name

### ISSUE THREAD

**Issue by gidden** [IAMconsortium/pyam#110]
at present, it will fill in with `np.nan`. I would argue that's not very helpful and we should require a column name be given. @danielhuppmann thoughts?

**Comment by gidden** [comment]
Ah yes, in my case I did the following:

```
ssps = df.meta.reset_index()['scenario'].apply(lambda x: 'SSP' + x.split('SSP')[1][0])
df.set_meta(ssps)
```

So that series did not get a name by default

**Comment by danielhuppmann** [comment]
Yes, pandas tends to do these things... It's a good catch of unexpected behaviour of `set_meta()`, almost there with the fix...
