### ISSUE TITLE
Name clash

### ISSUE THREAD

**Issue by khaeru** [IAMconsortium/pyam#118]
PyPI contains a packaged named [`pyam`](https://pypi.org/project/pyam/): “Python package for solving assortative matching models with two-sided heterogeneity.”

1. At the very least, the README/documentation should warn users not to try `pip install pyam` or similar.
2. If the package is to be published to PyPI, a different name is needed…maybe `iamc-pyam` or something?

**Comment by gidden** [comment]
Hi Paul -yes that's the plan. For aneris, I used aneris-iamc
https://pypi.org/project/aneris-iamc/

There is no such collision on conda forge.

**Comment by danielhuppmann** [comment]
@khaeru, can this issue be closed?

**Comment by khaeru** [comment]
> @khaeru, can this issue be closed?

Sure, done.

We still have problems (e.g. in the October tutorials for new research assistants) with people mistakenly trying to install the other "pyam" package, see e.g. iiasa/message_ix#237.

But I suppose that's something that can only be fixed by clearer documentation in packages that depend on this one.
