### ISSUE TITLE
Add License Badge

### ISSUE THREAD

**Issue by gidden** [IAMconsortium/pyam#121]
I messed up our last release such that it doesn't show the license badge. On the next one, make sure `"license": "Apache 2.0"` is in `setup.py` and add the following lines to `doc/source/index.rst`:

```
.. image:: https://img.shields.io/pypi/l/pyam-iamc.svg
    :target: https://pypi.python.org/pypi/pyam-iamc
```

**Comment by znicholls** [comment]
@gidden I think this can be closed?

**Comment by gidden** [comment]
Yup!
