### ISSUE TITLE
Installs are broken

### ISSUE THREAD

**Issue by znicholls** [IAMconsortium/pyam#131]
If one does:

```bash
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ pip install --upgrade pip
(venv) $ pip install pyam-iamc
```

then not all of the right dependencies are installed i.e.

```python
>>> import pyam
...
ModuleNotFoundError: No module named 'numpy'
```

This is solved by #120

**Comment by znicholls** [comment]
Perfect (sorry the issue was so short, was on a train in a rush)

**Comment by gidden** [comment]
@znicholls can you test again? Just uploaded 0.1.1 to pypi.

**Comment by znicholls** [comment]
Damn it

```python
>>> import pyam
ModuleNotFoundError: No module named 'requests'
```

**Comment by gidden** [comment]
Really? Requests is in the standard library I thought..

**Comment by gidden** [comment]
Ok, fixed in latest version
