### ISSUE TITLE
Link to tutorial in README.md points to non existant page

### ISSUE THREAD

**Issue by jtmiclat** [IAMconsortium/pyam#154]
Currently, the link to the tutorial in the README.md points to `tutorial/pyam_first_steps.ipynb` which does not exist. 

It should either point to `doc/source/tutorials/pyam_first_steps.ipynb` or the rendered docs page https://software.ene.iiasa.ac.at/pyam/tutorials/pyam_first_steps.html

**Comment by danielhuppmann** [comment]
closed by #175
