### ISSUE TITLE
pandas 0.24 compatibility issue

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#180]
Trying to fix compatibility with pandas 0.24, it seems that there is some problem with the use of `combine_first()` in the statistics module (plus a few minor issues where `reset_index()` keeps names now).

Currently hard-coded to use pandas 0.23.4 in #178, with some unexpected behaviour, see comment
https://github.com/IAMconsortium/pyam/pull/178#issuecomment-457957641

**Comment by danielhuppmann** [comment]
seems that the issues that broke unit tests were fixed in `pandas 0.24.1`

**Comment by znicholls** [comment]
fixed by pinning version in v0.2.0 so can close @danielhuppmann ?
