### ISSUE TITLE
v0.2.1

### ISSUE THREAD

**Issue by znicholls** [IAMconsortium/pyam#183]
@gidden any chance of a 0.2.1 (or 0.1.3) release so openscm has a pip installable version of pyam (we can't put a fully functioning version version on pypi with url dependencies)?

**Comment by gidden** [comment]
We can likely do another patch release, but not sure exactly when I will
have time to do so. How urgent is it?

Note to myself, I should make some release docs so others can do it to..

**Comment by danielhuppmann** [comment]
@gidden, if you have time, could you also update the docs pages - pretty please?

**Comment by gidden** [comment]
On the todo list =)

**Comment by znicholls** [comment]
> How urgent is it?

Not super urgent but would be handy to see if we can make openscm pip installable (and hence easily usable by other stuff).

If you want some release docs to copy, this might be helpful https://netcdf-scm.readthedocs.io/en/latest/development.html#releasing

**Comment by znicholls** [comment]
@gidden for packaging and sorting out backends, this would be super useful. At the moment I can't push any wheels to pypi because we're dependent on a specific commit of pyam and not a released version.

**Comment by gidden** [comment]
Agreed, this is on our radar. I was going to let @danielhuppmann give it a spin if he wants =) otherwise I can tackle this next week.

To open a slightly broader discussion - should we call it `0.2.0` or `0.1.3`? I feel like a lot has changed, so would probably suggest `0.2.0`. However, we don't have a guiding document yet on how to increment versions..

**Comment by danielhuppmann** [comment]
I‘d go for 0.2.0. And sorry, no chance I do this until the MESSAGEix postprocessing is implemented.

**Comment by gidden** [comment]
Understood!

**Comment by znicholls** [comment]
semantic would suggest v0.2.0 as you've got major new improvements?

**Comment by znicholls** [comment]
v0.2.0 released so closing this
