### ISSUE TITLE
region plotting breaks in geopandas 0.5.0

### ISSUE THREAD

**Issue by gidden** [IAMconsortium/pyam#227]
It appears region plotting is broken with the latest geopandas release, see attached MPL images (we lose France, among other countries). We should decide:

- do we support this new version and make us backwards incompatible?
- do we ask geopandas how best to adapt?
- do we make geopandas<0.5.0 a hard install requirement?

any thoughts @danielhuppmann or @znicholls 
![test_region-failed-diff](https://user-images.githubusercontent.com/1392657/56891605-59b4fb00-6a7d-11e9-8dc1-f4a517502f4b.png)
![baseline-test_region](https://user-images.githubusercontent.com/1392657/56891606-59b4fb00-6a7d-11e9-899f-ce8103fc62b3.png)
![test_region](https://user-images.githubusercontent.com/1392657/56891607-5a4d9180-6a7d-11e9-908b-0eb9cb3a9fdd.png)

**Comment by znicholls** [comment]
> do we make geopandas<0.5.0 a hard install requirement?

I would recommend this for current releases (and master). Then when you can be bothered, add geopandas>0.5.0 and make a new (backwards incompatible) release. I don't use mapping so I don't really mind and would prefer to see efforts focussed elsewhere (but if mapping is a priority for you guys, go for it).

**Comment by gidden** [comment]
Yes, I am +1 this as well for the moment. The problem with making these requirements is that you start to quickly become incompatible with other packages (that in the future have a ">0.5.0" req).

**Comment by znicholls** [comment]
I think at some point you (we) need to hit pause on development and upgrade both pandas and geopandas to be compatible with new versions. There's already conflicts with things that require pandas>0.24.0 and pyam. (I would also suggest streamlining the release process so they can be made more frequently at the same time, but let's see how things go.)

**Comment by gidden** [comment]
agreed. I think this is on @danielhuppmann's radar too

**Comment by danielhuppmann** [comment]
yes, it's on my radar - afaik, we are compatible with `pandas` 0.24.1 (they resolved the issue for `combine_first()` which caused unit tests to fail in 0.24.0). But the amount of `pandas` warnings on the latest version (replacing `labels` with `codes` etc.) makes looking at unit test output quite painful.

**Comment by danielhuppmann** [comment]
This is causing more issues with dependencies bumping their version numbers, see #260 for a quickfix - this PR needs to be reverted once we move to `geopandas==0.5.0` .

Also, readthedocs still claims to be failing to build on Travis, even though it passes...?

**Comment by danielhuppmann** [comment]
closing this issue because region-plots have been removed from pyam for the time being
