### ISSUE TITLE
pyam version

### ISSUE THREAD

**Issue by fallahnejad** [IAMconsortium/pyam#230]
Thank you for the interesting package.
It might rather be a request than an issue. I expected to get the pyam version once I enter:

`pyam.__version__`

Thank you for consideration.

**Comment by gidden** [comment]
Hi @fallahnejad, thanks for making an issue! One quick question - how did you install pyam (i.e., from conda, pip, source)? On the current master branch, you indeed get the version:

```
$ python -c 'import pyam; print(pyam.__version__)'
0.1.2+59.geb3c327.dirty
```

**Comment by fallahnejad** [comment]
Thanks for the fast reply.
well, I installed pyam via conda-forge channel: conda install -c conda-forge pyam

```
>>>pyam.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyam' has no attribute '__version__' 
```

I just checked in the anaconda navigator. I'm using pyam version 0.1.2.

**Comment by gidden** [comment]
Ok, that makes sense. After the `0.1.2` release, we switched to using `versioneer.py` which provides the correct `__version__` attribute. We are in the process of making a new release now, so you should get that attribute upon the next release. 

I will close the issue for now, but let us know if you come across any other issues using the library!
