### ISSUE TITLE
`interpolate` does not follow other return conventions

### ISSUE THREAD

**Issue by gidden** [IAMconsortium/pyam#240]
We recently had a private communication regarding confusion with the `interpolate` function. The user was trying to do something like:

```
df_interp = df.filter().interpolate()
```

The returned object was *not* an interpolated dataframe. We advised the user as follows:

```
alldata = pyam.IamDataFrame(data='iamc15_scenario_data_world_r1.1.xlsx')
df = alldata.filter(variable='Emissions|CO2',scenario='SSP1-19') # save the filtered dataframe explicitly
df.interpolate(2063)  # interpolate the filtered dataframe
```

I would argue this breaks our implicit datamodel of dataframe methods returning a copy unless `inplace=True` is provided. 

@danielhuppmann can you provide your thoughts?

While making such a change would break existing API, I think there is a strong argument for all functions to conform to our (from `pandas`) data model.

**Comment by danielhuppmann** [comment]
I agree that this is a relevant change to ensure consistency.

This will break a number of the scripts for the IPCC SR15 at https://github.com/iiasa/ipcc_sr15_scenario_analysis. Guess I'll have to figure out a way to inform users where API changes past release 0.2.0 may cause problems.

**Comment by danielhuppmann** [comment]
Thinking about this for a second...

@gidden, the expected behaviour is to return the extended `IamDataFrame` (original plus the interpolated data)? Or should we add another kwarg (e.g, `append`) to control that?

So options would be: 
 1. `inplace=True, append=True`: current behaviour
 2. `inplace=True, append=False`: illegal
 3. `inplace=False, append=True`: suggested new default, return extended `IamDataFrame`
 4. `inplace=False, append=False`: return `IamDataFrame` of only the year to be interpolated

Follow-up question for option 4: should this return all rows for the interpolated year, or only those rows where that particular year was missing in the original data?

**Comment by gidden** [comment]
Here I think we are overloading the definitions of `inplace` and `append`. I would actually argue (against my earlier self) that `inplace` may not be correct here. 

Normally, if we have an operation with `inplace=True`, it implies a mutation of the dataframe and a return type of `None`, e.g., `df.reset_index(inplace=True)`. The main argument for doing this is to not make a copy.

However, we also have a convention within `pyam` to use the keyword `append`, which "translates" to: perform an operation (**not** a mutation) and append the result to the existing dataframe.

Here, interpolate is an *operation* and not a *mutation*. Thus, I would suggest only having `append` as a keyword. If `False`, then return the interpolated dataframe. If `True`, then append the data to the existing dataframe and return None.

**Comment by danielhuppmann** [comment]
ok, so we follow the (future) behaviour of [pyam.IamDataFrame.aggregate()](https://pyam-iamc.readthedocs.io/en/stable/api.html#pyam.IamDataFrame.aggregate) as discussed.

 - `append=False` (default): return `IamDataFrame´ with only newly interpolated values
 - `append=True`: append new values to `self`, return None

**Comment by gidden** [comment]
Sounds great to me!

**Comment by danielhuppmann** [comment]
Coming back to this issue, @gidden, I’m wondering what the motivation and actual use case of `append=False` is? Why would one want to have ONLY the interpolated data, and is this a useful default?

Going through this thread again, I think that `inplace` is the more intuitive kwarg, either making a copy with additional data (default, `False`),  or appending the data to the original `IamDataFrame`.
