### ISSUE TITLE
Pandas 0.25 breaks plotting

### ISSUE THREAD

**Issue by znicholls** [IAMconsortium/pyam#245]
Pandas 0.25 has removed `pandas.plotting._style`, it's now in `pandas.plotting._matplotlib.style`. Is there a way to avoid this reliance on a private module of pandas so this break doesn't happen in future (my brief look says no but just in case you have better ideas)?

**Comment by gidden** [comment]
Yeah, I wasn't happy about having to depend on a private module, but at the time saw no way around it. As a hotfix we can do something like 

```
try:
    from pandas.plotting import _style as plt_style
except ImportError:
    from pandas.plotting._matplotlib import style as plt_style
```

Maybe it's worth posting to the `pandas` mailing list to ask for guidance with our specific use case though..

**Comment by gidden** [comment]
To note, we are now running into this on downstream dependencies: https://github.com/iiasa/message_ix/pull/220
