### ISSUE TITLE
Unexpected behaviour in `stack_plot()`

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#266]
# Description of the issue

I've been trying to use the `stack_plot()` function for some follow-up [SR15](https://github.com/iiasa/ipcc_sr15_scenario_analysis) assessment, and noticed two major issues.

1) Timeseries data starting with zero are ignored completely
2) Multiple crossings of the zero baseline end up shown wrong

# Illustration

```
import pandas as pd
import pyam
df = pyam.IamDataFrame(pd.DataFrame([
    ['a', 1, 2, 3, 4],
    ['b', 0, 1, 2, 3],
    ['c', -1, 1, -1, 1],
    ['d', 1, 1, 1, -1]
    ],
    columns=['variable', 2010, 2020, 2030, 2040],
), model='model_a', scenario='scen_a', region='World', unit='some_unit')
df.stack_plot()
```

![image](https://user-images.githubusercontent.com/16931589/64333454-d4b39280-cfd6-11e9-867d-2eebe7ccfbdd.png)

# More insights

In the source of `stack_plot()`, there is this docstring...

```
    # Sort lines so that negative timeseries are on the right, positive
    # timeseries are on the left and timeseries which go from positive to
    # negative are ordered such that the timeseries which goes negative first
    # is on the right (case of timeseries which go from negative to positive
    # is an edge case we haven't thought about as it's unlikely to apply to
    # us).
```

**Comment by znicholls** [comment]
Nice pick up @danielhuppmann !

> 1. Timeseries data starting with zero are ignored completely

I think this can be fixed by altering https://github.com/IAMconsortium/pyam/blob/127680a8f412659c440655c4238c33cb45b528da/pyam/plotting.py#L475 to `pos_cols = [c for c in _df if (_df[c] >= 0).all()]` (`>=` rather than `>`)

> 2\. Multiple crossings of the zero baseline end up shown wrong

As you've seen in the comments, this case where a timeseries goes positive, then negative, then back again is a case we didn't work through. We were not sure how you'd even want to plot this (as you probably have to jump over another timeseries so you lose the continuity we were trying to get). New functionality for you to play with!

**Comment by danielhuppmann** [comment]
Thanks for the assist on fixing issue 1, @znicholls! Issue 2 is indeed a tricky beast...

**Comment by znicholls** [comment]
> Issue 2 is indeed a tricky beast

You could just have an `if` clause, based on something like https://github.com/IAMconsortium/pyam/blob/127680a8f412659c440655c4238c33cb45b528da/pyam/plotting.py#L449, which basically checks whether we're in the case where the lines are hopping back and forth across zero in an awkward way. If they are, you could skip all the steps which try to make the plot pretty and just plot it in a way which works and shows all the data. That will still require some mucking around but I think separating the strategies is a good idea as they are trying to achieve different things and apply in different cases.

**Comment by danielhuppmann** [comment]
I was thinking that splitting all timeseries data into a positive and negative component might do the trick... But making it pretty afterwards will be a pain.

**Comment by znicholls** [comment]
> I was thinking that splitting all timeseries data into a positive and negative component might do the trick... But making it pretty afterwards will be a pain.

Yep I think that's probably best. Keeping track of colours and joining lines etc. will be har. If you do it with loops initially I think it should be easier to implement and then it can be refactored to vector operations afterwards.
