### ISSUE TITLE
no logging output in Jupyter notebooks

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#293]
Following the merge of #288, there is no logging output written in Jupyter notebooks or ipython!

Is this a feature or a bug? (If it's a feature, it's not a great one).

**Comment by znicholls** [comment]
On the plus side it means our loggers are now actually properly namespaced. On the minus side very few understand Python's logging rules so this would confuse a lot of our userbase. Have a look at the fix in #294 and let's take it from there?

**Comment by danielhuppmann** [comment]
@znicholls, I looked through the two references you mentioned in #288, put I think I'm still in the group of users not really understanding logging rules...

**Comment by znicholls** [comment]
Ye they're not super easy. Logging is a bit of a rabbit hole for sure...
