### ISSUE TITLE
Add slightly more explicit example of df.filter(`exclude=False`) in tutorials

### ISSUE THREAD

**Issue by byersiiasa** [IAMconsortium/pyam#298]
Suggestion to slightly improve the example on use of `df.validate(criteria={...}, exclude_on_fail=True) `and `df.filter (exclude=False)`.

This is just above box 20 in the tutorial:
https://pyam-iamc.readthedocs.io/en/stable/tutorials/pyam_first_steps.html#Using-metadata-indicators-for-further-scenario-characterization-&-diagnostics

An example, which I think would be a common use case is this process of 
1. set exclude tags on data
2. filter the data, dropping the excluded data in the process
3. (view table / plot the "good" data)

Example would be helpful as the implementation is slightly counterintuitive in that first we `exclude_on_fail=True`, but then to exclude that data, the argument in `df.filter` is `exclude=False`

**Comment by danielhuppmann** [comment]
thanks @byersiiasa for this suggestion!

**Comment by byersiiasa** [comment]
Resolved by https://github.com/IAMconsortium/pyam/pull/302 - thanks!
