### ISSUE TITLE
"Interpolate" only works for year-based values

### ISSUE THREAD

**Issue by Rlamboll** [IAMconsortium/pyam#328]
I'd hope that date-time dataframes could also be interpolated, but currently this just breaks, as the interpolation is hard-coded to use a column called 'year'.

**Comment by danielhuppmann** [comment]
Indeed, this feature is from the pre-datetime days...

But it should be quite straightforward to add a switch `if self.time_col == 'year'` and add treatment for continuous-time. Want to give this a first shot @Rlamboll?

**Comment by Rlamboll** [comment]
I think so, when is the next iteration of updates scheduled for?

**Comment by danielhuppmann** [comment]
were planning a patch release soon to ensure compatibility with the just-released pandas v1.0, but the next minor release could happen soon after that - if there are some nice new features ;-)

**Comment by Rlamboll** [comment]
I've done the coding for this but don't have permission to push to the github. 
Also, in order to fix this I use fill_series with date-times. This works perfectly with the existing codebase, but I am interpreting the word "year" to mean "time", so I'd normally rename that to "time", which sounds more general. I have renamed the only use in the pyam codebase but this may break things outside of it, so I'm just warning people.

**Comment by danielhuppmann** [comment]
Awesome, looking forward to review! Can you please create a fork of the repo, create a branch there, and start a PR into `IAMconsortium:master`? Better than pushing directly to the main repo.

About the API change - maybe the `fill_series()` can still do the casting from `int` to `datetime` (if necessary) for backwards compatibility (and user friendliness going forward)? If not, see this example for an example of how to properly warn users about [API changes](https://github.com/IAMconsortium/pyam/blob/master/RELEASE_NOTES.md#api-changes).

**Comment by Rlamboll** [comment]
Solved by #334
