### ISSUE TITLE
Initializing with `None` entries in IAMC_IDX columns

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#336]
# Problem description

As (again) identified by @fonfon, initialising an `IamDataFrame` with `None`/`nan` in the `IAMC_IDX` columns (model, scenario, region, variable, unit) will silently drop these columns. This is necessary because `pandas` has issues with `None`, but it can lead to unexpected behaviour.

# Suggested solution

Separate this section of the code https://github.com/IAMconsortium/pyam/blob/7d46b2c1c3a46d799c1b09dbabc9dbe88e80ee07/pyam/utils.py#L250 
into two parts:
1) remove all `nan` in the `value` column
2) raise an error if `nan` are present in the remaining dataframe

## Alternative

Add a keyword argument to use a default value, maybe an empty string (`''`)?

## Test

The test could be based on this exmaple:
https://github.com/IAMconsortium/pyam/blob/7d46b2c1c3a46d799c1b09dbabc9dbe88e80ee07/tests/test_core.py#L43

**Comment by danielhuppmann** [comment]
@gidden @znicholls any comments?

**Comment by znicholls** [comment]
Suggested options look good. Id always drop nan in the value column. I’d be tempted to make the default behaviour for nan in other columns an error, with a keyword argument available that the user can use to specify the fill value for missing values (rather than an empty string which could do odd stuff).

**Comment by danielhuppmann** [comment]
@fonfon implemented the "raise error if nan (other than `value` col)" for now - let's re-open this issue if we need the more sophisticated "replace nan in non-`value` col via kwarg"...
