### ISSUE TITLE
list of required dependencies doesn't show up

### ISSUE THREAD

**Issue by maxtav** [IAMconsortium/pyam#363]
https://pyam-iamc.readthedocs.io/en/stable/install.html

missing list of required dependencies

**Comment by danielhuppmann** [comment]
Thanks @maxtav for identifying this bug - my mistake when updating the docs for the last release.

**Comment by gidden** [comment]
Thanks @danielhuppmann for the fix, and thanks @maxtav for bringing it to our attention!
