### ISSUE TITLE
Filter for datetime (or year) won't accept numpy arrays

### ISSUE THREAD

**Issue by Rlamboll** [IAMconsortium/pyam#367]
Filter will not accept numpy arrays of timelike values. This seems odd, given that if one extracts the unique elements of the date or year, it is in this format. Here's a minimal case replication: 
____
import pyam
import pandas as pd
import datetime as dt

_msa = ["model_a", "scen_a"]
db_dt = pd.DataFrame(
    [
        _msa + ["World", "Emissions|HFC|C5F12", "kt C5F12/yr", 2, 3],
        _msa + ["World", "Emissions|HFC|C2F6", "kt C2F6/yr", 0.5, 1.5],
    ],
    columns=[
        "model", "scenario", "region", "variable", "unit", dt.datetime(year=2010, day=1, month=1), 
        dt.datetime(year=2015, day=1, month=1)],
)
db_dt = pyam.IamDataFrame(db_dt)
db_dt.filter(time=db_dt["time"].unique()[0])
____
This seems to fail similarly with years (won't accept int64 arrays either), although the error message is more cryptic. It works normally if  I convert the numpy array to a standard array. Is this desired behaviour?

**Comment by danielhuppmann** [comment]
This is definitely not desired behaviour...

The type you are passing is `numpy.datetime64`, which triggers this consistency check [here](https://github.com/IAMconsortium/pyam/blob/8ead13e1f40121a580714f3293c6195b59919d87/pyam/utils.py#L426).

**Comment by Rlamboll** [comment]
Solved by #370 370
