### ISSUE TITLE
`interpolate` fails if 'accidently applied twice'

### ISSUE THREAD

**Issue by gidden** [IAMconsortium/pyam#371]
If the exact same interpolate call is used twice, the underlying data layout is appended in both `wide` and `long`.

Example code:

```
df.interpolate(2016) # works
df.interpolate(2016) # bad data now
```

Image attached
![interp](https://user-images.githubusercontent.com/1392657/80870950-00903080-8caa-11ea-88cd-4f7d78cbe855.png)

**Comment by danielhuppmann** [comment]
Interesting, because we do have a test specifically for calling that function twice...

https://github.com/IAMconsortium/pyam/blob/063875bdb73f270d37b829c4c58ac7ec4e17ac53/tests/test_core.py#L710

**Comment by danielhuppmann** [comment]
@gidden could you make a PR with a test that fails with this specific issue?
