### ISSUE TITLE
interpolate function raises Error when getting a numpy.int64

### ISSUE THREAD

**Issue by l-welder** [IAMconsortium/pyam#376]
Hi pyam-developer-team,

the interpolate function in the core module raises an error when it get a numpy.int 64 value:

![grafik](https://user-images.githubusercontent.com/39761230/81816012-064c0880-952b-11ea-818d-24d83c44feb4.png)

I was able to fix this locally by casting the numpy.int64 to a regular int... @gidden mentioned that this might happen because of my windows OS... I do not know if it is maybe worthwhile to adapt the interpolate function to avoid this error?

**Comment by danielhuppmann** [comment]
Thanks @l-welder for raising this issue - it was fixed (supposedly) in #370, but that was after the release v0.5.0. I assume that you installed from pip or conda?

Can you try installing from the master branch on GitHub and check if this solves your problem?

**Comment by danielhuppmann** [comment]
@l-welder did you try to install the latest version from master and can you confirm whether this issues still is solved there?

**Comment by danielhuppmann** [comment]
This should be fixed with release 0.6.0, please re-open if the issue persists
