### ISSUE TITLE
Return-type of `iiasa.Connection.query()` not IamDataFrame

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#378]
Working on some improvements to the integration of the IIASA-database-integration, and I'm wondering why the return-type `iiasa.Connection.query()` is a `pandas.DataFrame`, not an `IamDataFrame` - which would be more logical.

@gidden, any particular reason? And any objection to casting the returned dataframe as `IamDataFrame` directly (instead of having to do `df = pyam.IamDataFrame(iiasa.Connection(<name>).query(...))`)?

**Comment by gidden** [comment]
No strong reason
