### ISSUE TITLE
Removing old installation eggs

### ISSUE THREAD

**Issue by byersiiasa** [IAMconsortium/pyam#381]
I can across a difficulty recently in updating pyam from master.
When importing it in jupyter notbeook it was finding the wrong old version despite attempts to install with pip and setup.py

More inspection revealed two things:

1. That there was a nest of old eggs in the `site-packages` folder of the environment,
2. that my `sys.path` also had these old eggs specifically listed, in chronological order, so it was always finding the oldest version first.

Is it expected behaviour that the old eggs stay in `site-packages` when updates are installed? is it necessary to keep them, otherwise removing them could reduce chance of errors

**Comment by byersiiasa** [comment]
e.g.
![image](https://user-images.githubusercontent.com/17701232/82887290-165ee180-9f48-11ea-87f9-0802dd5202bd.png)
![image](https://user-images.githubusercontent.com/17701232/82887306-1bbc2c00-9f48-11ea-9e05-3e041b188348.png)

**Comment by byersiiasa** [comment]
BTW - removing said items from `path` and the folders from the dir fixes the issue

**Comment by danielhuppmann** [comment]
Closing as this seems to be a general "how to install packages from source" issue, not directly related to pyam... Please re-open if I misunderstood the issue and it needs to be fixed in pyam.
