### ISSUE TITLE
Unit conversion with "-equiv"

### ISSUE THREAD

**Issue by Rlamboll** [IAMconsortium/pyam#383]
Silicone converts units using the depricated 'factor' method. This means every time I convert units, I get a warning. However since the current pint implementation doesn't work when there's a (functionally irrelevant) "equiv" in strings, there doesn't appear to be any other way to do this consistent with how we name units. The factor itself is collected from pint after cleaning out the "-equiv" strings, so would work if we did that. Can we either un-depricate the factor method or make the other method work for this common use-case?

**Comment by danielhuppmann** [comment]
I’m confused - which factor-method was deprecated?

**Comment by Rlamboll** [comment]
The method using a dictionary of units to factors:
to_convert_df.convert_unit({unit: [convert_to_str, conversion_factors[unit]]})

**Comment by danielhuppmann** [comment]
Got it, thanks for the clarification! We didn't deprecate the option to use an explicit factor, just changed the API from a dict to keyword arguments for clarity. So if you replace that line by 
```
to_convert_df.convert_unit(current=unit, to= convert_to_str, factor=conversion_factor)
```
it should work as before (without warning).

Also, pint has issues with using `-` in any strings, but it might be a simple fix to just add `CO2-equiv` to the `SPECIES_ALIAS` mapping in `pyam/units.py`.

**Comment by Rlamboll** [comment]
That does indeed fix the problem, thanks! Re. the new suggestion, that will entirely solve the problem for me and in most cases, but in principle there could also be equivs for other things.

**Comment by danielhuppmann** [comment]
Great - would you mind starting a little PR adding this alias for `CO2-equiv` and then close this issue? (and we can add more aliases when we find them).

**Comment by Rlamboll** [comment]
The way I'm attempting to do it gets an 'unsupported operand' error for the '-', which I think is why we suggested to move away from doing this in the first place. I don't know enough about pint to tell if there's a workaround.

**Comment by danielhuppmann** [comment]
If you're adding the line
```
    'co2-equiv': 'CO2e',
```
to the `SPECIES_ALIAS`, this shouldn't even arrive in pint...?

**Comment by Rlamboll** [comment]
It does because you test whether things convert with pint before trying anything else. I've just scrubbed -equiv from strings before converting them now, see how that is in #386
