### ISSUE TITLE
Regional downscaling using explicit weight dataframe

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#400]
To implement a more versatile **downscale_region()** feature (required by @maartenbrinkerink), we'll add the functionality to pass a weighting-dataframe instead of using a variable (within the IamDataFrame) as a proxy.

The question is whether to
1) re-use the existing **proxy** arg (so that this can be either a string pointing to a variable or a dataframe with weights)
2) make proxy optional and add a second **weight** kwarg (or other name)

@gidden @l-welder, any preferences?

**Comment by l-welder** [comment]
Hi @danielhuppmann ,

I feel that I cannot make an informed statement on this as of right now. If you want to make a decision on this soon, I think I would go for the second option (as I think that switching from this one back to the first one is easier than vice versa). What do you think?

**Comment by l-welder** [comment]
@danielhuppmann @gidden,

do we want to open a feature branch for this? Or how do you do things here? (normally I would make a fork and at some point push the feature branch back)

**Comment by danielhuppmann** [comment]
replying to @l-welder:

> do we want to open a feature branch for this? Or how do you do things here?

@maartenbrinkerink will take the lead on the weight-dataframe feature via his fork - should be ready to be merged to `IamConsortium:master` by the end of the week, it's probably only 10 lines of code plus one test.

For adding more sophisticated methods to the regional-downscaling as discussed last week, we try to follow the standard route:
 - start an issue to discuss API choices
 - fork and implement as a feature branch
 - review and merge

**Comment by danielhuppmann** [comment]
replying to @l-welder:

> I think I would go for the second option

That was also my thinking, so that is what I recommended @maartenbrinkerink to try

**Comment by gidden** [comment]
I would suggest we add a `method` arg which defaults to `proxy`. each method can then be implemented as its own function which can be tested and documented. the `downscale_region()` function would then act as a single API entry point which then calls `downscale_region_proxy()` with arguments.

This would be similar to how pandas implements plots (i.e., you have `df.plot(kind='bar')` or `df.plot.bar()`.

**Comment by danielhuppmann** [comment]
This has been (mostly) implemented by #411, so I'm closing this issue.

@l-welder, can you create a new issue for discussing the more sophisticated downscaling methods?
