### ISSUE TITLE
Orphan branches

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#404]
There are a number of orphan branches (actually stages of a few linear branches) created by @znicholls in the main repository.

- `reorganise-df-tests`
- `add-openscm-iam-df-links-2`
- `add-openscm-df-class-2`
- `add-magicc-variable-infilling`
- `add-openscm-iam-df-links`
- `add-openscm-df-class`
- `split-out-base-class`

Can these branches be safely deleted?

**Comment by znicholls** [comment]
ooops yep removed
