### ISSUE TITLE
SSLError running Connection()

### ISSUE THREAD

**Issue by thompsoa** [IAMconsortium/pyam#414]
When trying to connect to the IIASA data sources using 

```
import pyam
conn = pyam.iiasa.Connection()
```

I get an SSLError

`SSLError: HTTPSConnectionPool(host='db1.ene.iiasa.ac.at', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))`

I'm using Python 3.7.3 via Anaconda on Windows 10. I have the latest version of openssl (1.1.1g) and have never had any SSL errors when running python code or updating packages before.

**Comment by danielhuppmann** [comment]
thanks @thompsoa for reporting this error, sorry for the inconvenience! @zikolach, do you know if that is an IIASA-specific error (ie invalid SSL certificate) or a (mislabelled) generic connection error?

**Comment by danielhuppmann** [comment]
@thompsoa we cannot identify any direct problem - could this be a problem of an unstable internet connection (so that it was a timeout rather than an SSL certificate problem)? does the problem persist, and can you replicate it from another device?

**Comment by danielhuppmann** [comment]
@thompsoa do you still have that problem?

**Comment by danielhuppmann** [comment]
Nlosing as no response to this issue or reports of similar problems, should be more stable going forward by testing the pyam-IIASA API against a dedicated Scenario-Explorer-database instance
