### ISSUE TITLE
When appending inconsistent dfs in the new pyam, inplace=True suppresses errors

### ISSUE THREAD

**Issue by Rlamboll** [IAMconsortium/pyam#434]
As the title indicates. the new pyam appears to produce a viable output when appending dfs with different numbers of meta columns. It will discover it is broken at a later point. 
Example code: 

import pyam
import pandas as pd
_mc = "model_c"
_sa = "scen_a"
_sb = "scen_b"
_eco2 = "Emissions|CO2"
_gtc = "Gt C/yr"
_ech4 = "Emissions|CH4"
_mtch4 = "Mt CH4/yr"
_msrvu = ["model", "scenario", "region", "variable", "unit"]
simple_df = pd.DataFrame(
    [
        [_mc, _sa, "World", _eco2, _gtc, 0, 1000, 5000],
        [_mc, _sb, "World", _eco2, _gtc, 1, 1000, 5000],
        [_mc, _sa, "World", _ech4, _mtch4, 0, 300, 500],
        [_mc, _sb, "World", _ech4, _mtch4, 1, 300, 500],
    ],
    columns=_msrvu + [2010, 2030, 2050],
)
simple_df_2 = pyam.IamDataFrame(simple_df)
simple_df["model"] = simple_df["model"] + "_original"
simple_df["meta"] = "Joke goes here"
simple_df = pyam.IamDataFrame(simple_df)

# an error is produced if I add inconsistent dataframes normally:
try: 
    simple_df.append(simple_df_2)
except Exception as e:
    print(e)
# But no error if inplace.
simple_df.append(simple_df_2, inplace=True)
# It is quietly broken
simple_df.variables()

**Comment by danielhuppmann** [comment]
Thanks for raising this issue @Rlamboll - just for clarity, this also didn't work before (and It isn't supposed to), just the error message was lost/postponed due to the back-end refactoring.

**Comment by Rlamboll** [comment]
I don't think anyone actually approved that request. And while it fixes this bug, it doesn't test the bug is fixed.
