### ISSUE TITLE
Average with negative weights

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#446]
## Problem description

In several contexts, we discussed how to compute weighted averages when the weights are negative. The prime use case for this is an average carbon price over several regions, weighted by the (possibly negative) emissions in each region.

The current implementation of the [aggregate_region](https://pyam-iamc.readthedocs.io/en/stable/api/iamdataframe.html#pyam.IamDataFrame.aggregate_region) implements a direct weighted sum:

> value * weight / sum(weight)

This can lead to very counter-intuitive results - see more below.

## Illustration

Use the following snippet to explore the current behaviour:
```
def test_aggregate(value, weight):

    TEST_DF = pd.DataFrame([
        ['reg_a', 'Price|Carbon', 'USD/t CO2', value[0]],
        ['reg_b', 'Price|Carbon', 'USD/t CO2', value[1]],
        ['reg_a', 'Emissions|CO2', 'Mt CO2', weight[0]],
        ['reg_b', 'Emissions|CO2', 'Mt CO2', weight[1]],
    ],
        columns=['region', 'variable', 'unit', 2010],
    )

    return pyam.IamDataFrame(TEST_DF, model='model_a', scenario='scen_a')\
        .aggregate_region('Price|Carbon', weight='Emissions|CO2')._data.iloc[0]
```

1. If the sum of the weights is zero, the resulting average price is infinite
    ```
    test_aggregate(value=[1, 2], weight=[-1, 1])
    >>> inf
    ```
2. Depending on the order of the weight vector, it can also be negative infinity.
    ```
    test_aggregate(value=[1, 2], weight=[-1, 1])
    >>> -inf
    ```
3. If `sum(weight) == 0` and `value * weight == 0`, the returned value is `nan`, which is dropped when initiatilizing the IamDataFrame.
    ```
    test_aggregate(value=[1, 1], weight=[-1, 1])
    >>> Error
    ```
4. Other values can lead to situations where the "average" price is outside the range `min(value), max(value)`, e.g.
    ```
    test_aggregate(value=[1, 2], weight=[-1, 2])
    >>> 3
    ```

## Possible solutions

1. Leave as is, because it's up to the users to know this (including modeling teams uploading to the IIASA Scenario Explorer).

2. Leave as is, but write a warning message when weights are negative (question is whether users just ignore this).

3. Raise an error when any weight is negative, forcing users to explicitly choose an alternative approach (average, min, max).

4. Use the absolute of the weight vector. If there are three regions with emissions -1, 0 and 1, this would mean that the prices of region 1 and 3 are given equal weight and region 2 is ignored. This seems wrong...

5. Redefine the mathematical expression to 

    > value * weight / sum(abs(weight))

    However, this can also lead to strange outcomes, e.g., if all regional values are identical, and the weighted average is different.

6. Apply normalization (recalculate the weight vector such that `min(weight) == 0` and `max(weight) == 1`, leaving the relative distribution as is. This means that the price of the region with the lowest emissions is ignored (because its weight is 0).

7. Apply some shift/offset to make all weights positive. Suggestion by @byersiiasa: `weight = weight + 2 * min(weight)`.
    The vector `weight=[-1, 2]` would become `[1, 4]`.
    ```
    test_aggregate(value=[1, 2], weight=[1, 4])
    >>> 1.8
    ```
   This has the drawback that the offset multiplier is arbitrary - using a multiplier of 3 instead of 2 gives different results...
    ```
    test_aggregate(value=[1, 2], weight=[2, 5])
    >>> 1.7142
    ```

8. **Added** Write a warning when weights are negative and add a keyword-argument whether to drop (default) or not any values aggregated with negative weights.

9. **Added** Same as 8, but default is to include aggregation with negative weights.

10. Any other ideas...?

## Note

The function `numpy.avg()` faces the same problem. The devs decided to leave the unintuitive behaviour (solution 1 above), see https://github.com/numpy/numpy/issues/9825.

**Comment by danielhuppmann** [comment]
@volker-krey @byersiiasa @peterkolp @gidden @khaeru @OFR-IIASA @l-welder @gunnar-pik @Rlamboll, please share your thoughts or ping other colleagues who might have relevant insights... (or select Unsubscribe on this page if you don't want to be bothered with notifications about this thread).

**Comment by volker-krey** [comment]
There is plenty of discussion in various forums on this topic. The mathematical definition appear to require weights to be positive (https://en.wikipedia.org/wiki/Weighted_arithmetic_mean#Mathematical_definition). I would simply refrain from calculating a weighted average in case of et least one weight being negative. If you do something else, there will be users who misinterpret the outcome as they were not aware of whatever non-standard assumption you make (e.g. switching to absolute value for weights).

**Comment by Rlamboll** [comment]
Yeah, I can't see how you could describe it as an average when it anticorrelates with one of the constituents. You would just use the abs value as the weight. However without wanting to divide by the weight sum, this is just the aggregation function that we discussed here #355, which I use a lot (in Silicone) for constructing remainders.

**Comment by gunnar-pik** [comment]
Thanks @danielhuppmann, good to have this discussion! How about using a different weight, such as population or GDP or Final energy demand? This gives a decent indication of the system size of the regional entities. Not perfect, but in my view better than any of the other alternatives.

**Comment by byersiiasa** [comment]
so the rationale on 7 is to preserve the ratios between the weights, but adjust them in a way to make them all positive. (what I proposed above of adding above doesn't preserve the ratios however) 

It doesn't matter if the weights are [1,2] or [10,20]; the resultant weighed average will be the same if the ratios between the weights are preserved and that is normally the main aim. this falls apart when a weight is 0 or below.

So the `2*min(weight)` factor is to offset the lowest weight to it's absolute equivalent (e.g. make -2 into 2), and then increase all other weights by the same amount. But this doesn't preserve the ratio, but at least the absolute differences in emissions between the regions are the same (perhaps that is desirable?)

Alternatively,, whilst I'm not sure how quite, but what if the adjustment of the other weights can be done in a way that makes the lowest weight positive, and then adjusts (e.g. multiply, not add) all the others in a way to preserve the ratio between the weights?

***

on 6. - there are other "re-scaling" options that preserve the statistical distribution between the weights, if setting the lowest value to 0 is undesirable. E.g. min weight could be given a weight of 1 instead.

I also quite like the Final Energy suggestion of @gunnar-pik

**Comment by khaeru** [comment]
Principle of minimum surprise would suggest: don't do something different than numpy, so certainly not (4) through (7). Definitely do not have different behaviours depending on the particular variable names in use, as suggested in the last two comments.

Of (1), (2), and (3), I would exclude (3), since the numpy thread points out this is _mathematically_ valid, albeit perhaps without a common or obvious application in IA modeling. Between (1) and (2) it's a toss-up and I think depends on the intended user base; if they're likely to make this mistake and unlikely to read the docs carefully, then a warning could help.

**Comment by volker-krey** [comment]
I would argue that there will be different awareness of what's happening between (i) direct pyam users, and (ii) the users of the Scenario Explorer that will not know much about what is happening in the scenario processing pipeline. In the former case, issuing a warning as proposed in (2) seems reasonable to me. In the latter case, I would have a pretty strong preference for not calculating a finite value, but use instead NA (or similar) so that test case 4 does not materialize. Assuming an ignorant user that has not read any documentation is probably the safest choice here.

**Comment by danielhuppmann** [comment]
Thanks for all comments so far!

There are several levels to this question:
1. what/how to implement or change the behaviour in pyam?
2. whether/how to use this pyam feature in the IIASA Scenario Explorer processing pipeline
    (aggregation is currently implemented independently there)
3. how to configure (project-specific) the scenario protocols and processing pipeline to mitigate the problem
    (suggestion by @gunnar-pik to use a different variable for a carbon-price, would need to be discussed)

For now, this discussion should remain focused on the first question.

Based on @volker-krey's comment, I added two additional options/suggestions in the description above (repeated here for clarity):

> 8. Write a warning when weights are negative and add a keyword-argument whether to drop (default) or not any values aggregated with negative weights.

> 9. Same as 8, but default is to include aggregation with negative weights.

So in 8, the default behavior would be @volker-krey's suggestion, with a simple way to switch to option 2, with a warning in either case. This default goes against @khaeru's preference of "doing the same as numpy", but reduces the risk of confusing or misleading results. I therefore think that 8 is the best solution.

**Comment by byersiiasa** [comment]
I agree this all makes from software perspective. 

How / where to have the discussion regarding actual implementation to resolve the problematic issue of when the desirable weights , e.g. Emissions, go negative?
