### ISSUE TITLE
Allow undefined units?

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#453]
Currently, pyam raises an error when initializing from a pandas.DataFrame with `nan` or when reading from xlsx/csv with empty cells in any index/coordinate dimension. This makes sense for model, scenario, variable and region, but there could be timeseries without a natural unit (e.g., population or number power plants  if not given in an order of magnitude, shares, probabilities if given on the range [0, 1]).

The reason why this was introduced in the first place is that pandas has issues when filtering and other operations when `nan` are present.

One solution could be to allow variables without units by replacing `nan` with `''` (an empty string). That way, filtering and other operations should behave as expected, and writing to csv/xlsx should again generate empty cells (same as the original when reading from a file).

**Comment by danielhuppmann** [comment]
PS: the problem just materialized for me when trying to read default-generated MESSAGEix reporting output, which seems to not have units...

**Comment by danielhuppmann** [comment]
@gidden @znicholls @khaeru, any thoughts?

**Comment by znicholls** [comment]
> timeseries without a natural unit

Of the examples given, the typical pint unit is 'dimensionless'. Specifying that explicitly can be helpful, particularly if you ever want to add unit aware operations (e.g. https://github.com/openscm/scmdata/blob/master/notebooks/ops.ipynb https://scmdata.readthedocs.io/en/latest/scmdata.ops.html) in future.

I'm trying to think now, and I can't think of any timeseries which would actually have no unit but maybe my imagination is too limited.

You could simply assume dimensionless if nothing else is provided?

**Comment by danielhuppmann** [comment]
Good point, @znicholls!

pint parses `''` as `dimensionless`
```python
>>> pint.Quantity('1.0')
<Quantity(1.0, 'dimensionless')>
>>> pint.Quantity('1.0', '')
<Quantity(1.0, 'dimensionless')>
```
i.e., the empty string is "forward-compatible" for unit-aware operations using pint or iam-units.

So for convenience of non-expert users, I would still go with the empty string. Otherwise, this will cause a lot of confusion when users import an xlsx or csv with empty cells in the unit column and then have to do `df.filter(unit='dimensionless')` rather than `df.filter(unit='')`...

For examples of unitless variables:
 - population (if not given in an order of magnitude)
 - number power plants (if not given in an order of magnitude)
 - shares
 - probabilities if given on the range [0, 1]

In the IAMC 1.5°C (IPCC SR15) context (see [this workspace](https://data.ene.iiasa.ac.at/iamc-1.5c-explorer//#/workspaces/share/8d3927c5-b47b-4a05-9167-a84d184148eb)), we used `-` for temperature exceedance probability, but this is not pint-compatible and was a sub-smart choice...

**Comment by znicholls** [comment]
> For examples of unitless variables

I'm not sure I agree with any of these, I would say all of these are either 'dimensionless' or some derived unit based on mole. The point here being that I can't see any case in which you'd want to encourage not having a unit.

Irrespective of that, passing empty string to empty string sounds like a good solution to me.

**Comment by danielhuppmann** [comment]
Ok, let's call them dimensionless rather than unitless...

> Irrespective of that, reading empty of missing cells as an empty string for units sounds like a good solution to me.

Great!

For completeness: For me, the point is less about whether we want to encourage bad behavior but rather how we can make pyam useful given the bad practices already out there. Like when I tried to use pyam with a standard national-model MESSAGE reporting and had to jump through some hoops because the colleague had not defined units.
