### ISSUE TITLE
Proposal to read in multiple sheets (from Excel)

### ISSUE THREAD

**Issue by byersiiasa** [IAMconsortium/pyam#479]
Planning to extend `pyam.IamDataFrame()` such that if the excel file has multiple sheets, they are each read in and concatenated.

Proposal would be to either:

- accept sheets if starting with "data", e.g. data1, data2, etc.. (could be automatically?)
- accept a`str` or `list` of sheetnames, e.g. `sheetname=...`

Any preferences or other suggestions?

**Comment by danielhuppmann** [comment]
You can already pass a sheet-name to the IamDataFrame initialization, see 
https://github.com/IAMconsortium/pyam/blob/dd229ea01b11b0d98e9bb93086f8f75d76e2eeda/pyam/core.py#L96

Lists are an obvious extension (maybe it works already) and this could be extended to accept `*` as wildcard (e.g., `sheetname='data*').
