### ISSUE TITLE
Change fill_between to accept percentile range instead of min-max

### ISSUE THREAD

**Issue by byersiiasa** [IAMconsortium/pyam#480]
Currently lineplot has option `fill_between=True` which shades the min-max ranges between a model, or other argument that is passed to `color`, e.g. scenario or a column in the meta (iirc).

The proposal would be to keep the default option of min-max, but allow passing the option of percentiles (quantiles), e.g. 0.1, 0.9
. Given there is already the option of passing a dictionary to control the `alpha`, suggest to extend this with `quantiles`, e.g.`

`df.plot.line(... color='model', fill_between={'quantiles':[0.1,0.9]},...)`

Noting that this also potentially has implications for `final_ranges`

**Comment by danielhuppmann** [comment]
This is implemented via #686, see this tutorial https://pyam-iamc.readthedocs.io/en/stable/tutorials/quantiles.html. Thanks @gidden!

**Comment by byersiiasa** [comment]
awesome - had totally forgotten about this ;)
