### ISSUE TITLE
Regression: `IamDataFrame.load_meta` with csv filename string broken

### ISSUE THREAD

**Issue by coroa** [IAMconsortium/pyam#495]
PR #491 removed the wrapping of the `path` variable into `pathlib.Path`:

https://github.com/IAMconsortium/pyam/commit/3d31fdd36f9b1ca6088eadbc01d23857b9fab4ae#diff-473e3e462e12aec320a41b983e95a130a194c4700b63a0a5f97f153b899129e7L1737-R1745

Which has a call like `idf.load_meta("test.csv")` try to read the csv file with `pd.ExcelReader` in `read_pandas` at

https://github.com/IAMconsortium/pyam/blob/3d31fdd36f9b1ca6088eadbc01d23857b9fab4ae/pyam/utils.py#L116-L120

I'd suggest to put a
```
path = Path(path)
```
wrapper before line 116.

**Comment by danielhuppmann** [comment]
Thanks for raising this issue @coroa - I never thought that users would try to read a `meta` table as a csv file... But you're right, the docstring is agnostic to the type of file.

**Comment by coroa** [comment]
Thanks for addressing this so quickly!
