### ISSUE TITLE
Variables get sorted alphabetically before aggregating

### ISSUE THREAD

**Issue by pjuergens** [IAMconsortium/pyam#524]
When aggregating variables in an IamDataFrame df, the variables get sorted alphabetically before aggregating. With the standard method (addition) there's no problem, but when using np.diff, the result depends on the name of the variables instead of the order given in the components-list.

`
df.aggregate(variable='Net Imports',
                     components=['Imports', 'Exports'],
                     method=np.diff,
                     append=True)
`

It get's even more problematic, when using a more complicated custom method for calculating aggregation (which may exceed the intended use of the aggregate function, but could still be very useful as there is no "calculation-function" yet)

**Comment by pjuergens** [comment]
In relation to #332 #333 and #460 I'd propose a function that behaves somewhat like this:

```python
# define any function you want to calculate
def custom_calculation(a, b, c):
    return a + b / c

# calculate a new variable with this function
df.calculate(variable='New Variable',
              component=['First Variable', 'Second Variable', 'Last Variable'],
              method=custom_calculation,
              unit='TWh', append=True)
```

**Comment by danielhuppmann** [comment]
Thanks @pjuergens for this suggestion! This is perfectly in line with the work started by @gidden in #333 - if you are willing to take the lead in the implementation, I'd be happy to pull out the relevant parts from the initial PR into a new PR (and resolve all merge conflicts and inconcistencies that have accumulated over the past year) so that you can then work on a clean calculation-implementation.

**Comment by pjuergens** [comment]
I cannot promise to solve the problem in a proper way, but would like to try :)

**Comment by danielhuppmann** [comment]
Closing this issue after merging #527 and having started issues for the specific additional features discussed here and in that PR...
