### ISSUE TITLE
Support binary operations with numerical values

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#530]
Per a suggestion by @Rlamboll at https://github.com/IAMconsortium/pyam/pull/527#issuecomment-834279598 (and a bilateral comment by @OFR-IIASA), it would be a nice feature to extend the data-ops functions to take a numerical value, e.g.,

```python
df.multiply("Primary Energy", 3, "Primary Energy (end-use accounting)")
```

**Comment by pjuergens** [comment]
I think I kind of implemented that feature in the apply-function for additional keyword arguments, see #533 . It should be possible to adapt that approach for the binary operations as well
