### ISSUE TITLE
IPCC AR6-RCP colors are in wrong order

### ISSUE THREAD

**Issue by mkrapp** [IAMconsortium/pyam#554]
The list of colors as given here [https://pyam-iamc.readthedocs.io/en/latest/tutorials/ipcc_colors.html](https://pyam-iamc.readthedocs.io/en/latest/tutorials/ipcc_colors.html) are in the wrong order, at least for the AR6-RCP color codes

ID     | name              | color
-- | -- | --
14 | AR6-RCP-2.6 | #980002
15 | AR6-RCP-4.5 | #c37900
16 | AR6-RCP-6.0 | #709fcc
17 | AR6-RCP-8.5 | #003466

and should be 
ID     | name              | color
-- | -- | --
14 | AR6-RCP-2.6 | #003466
15 | AR6-RCP-4.5 | #709fcc
16 | AR6-RCP-6.0 | #c37900
17 | AR6-RCP-8.5 | #980002

 I haven't check the other IPCC colors.

**Comment by danielhuppmann** [comment]
Thanks @mkrapp for reporting this issue!

@gidden, it seems that something went wrong in #547 - can you please take a look?

**Comment by gidden** [comment]
Nice catch @mkrapp, thanks!

I've confirmed by hand with a spot check

```
rcp45 = [84, 146, 205]

scen = rcp45
rgb = np.array(scen) / 256
print(matplotlib.colors.rgb2hex(rgb))
```

=>

```
#5491cc
```

**Comment by gidden** [comment]
When running all the hex values, I get

```
rcp85 #980002
rcp60 #c37900
rcp45 #5491cc
rcp26 #003466
```

@mkrapp this is based on the attached revised color pallate from the TSU that I received on April 17, 2019. my value for rcp45 differs from yours. would you mind checking quickly on your side?

[color schemes - corrected.xlsx](https://github.com/IAMconsortium/pyam/files/6810169/color.schemes.-.corrected.xlsx)

**Comment by gidden** [comment]
For posterity, here is the current test file for the IPCC color scheme. A quick check confirms the reverse order of only the AR6-RCP series of colors. 

![test_line_PYAM_COLORS](https://user-images.githubusercontent.com/1392657/125484740-42528d18-325e-4d4f-bf4f-bf6cd8bdbccd.png)

**Comment by mkrapp** [comment]
> When running all the hex values, I get
> 
> ```
> rcp85 #980002
> rcp60 #c37900
> rcp45 #5491cc
> rcp26 #003466
> ```
> 
> @mkrapp this is based on the attached revised color pallate from the TSU that I received on April 17, 2019. my value for rcp45 differs from yours. would you mind checking quickly on your side?
> 
> [color schemes - corrected.xlsx](https://github.com/IAMconsortium/pyam/files/6810169/color.schemes.-.corrected.xlsx)

I think your rcp45 values are wrong (see [https://github.com/IPCC-WG1/colormaps/blob/master/categorical_colors_rgb_0-255/rcp_cat.txt]()) and should be **RGB(112,160,205)** which is **#70a0cd** like it is in the `pyam` table reffered to in the beginning. But please doublecheck. I can confirm that the other values (rcp26, rcp70, rcp85) are correct.

**Comment by gidden** [comment]
Great, thanks for double checking this @mkrapp - I've contacted the TSU asking for official guidance
