### ISSUE TITLE
append a pyamDataFrame with different years, or with subannual

### ISSUE THREAD

**Issue by sandrinecharousset** [IAMconsortium/pyam#578]
When working on datasets for a case study exercise, it may happen that some of the datasets hold data on 1 year only... thus in the process of data creation it may be useful to be able to concatenate 2 IAMDataFrames which do not have the same years columns. It appears that the append method only works when the 2 IAMDataFrames have the same list of years

Same thing when trying to concatenate 2 IAMdataframes, one with a subannual column, and the other one without. Even if the list of years is the same, it doesn't work

In both cases the error message is the same:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "XXX\pyam\core.py", line 427, in append
    raise ValueError('Incompatible timeseries data index dimensions')
ValueError: Incompatible timeseries data index dimensions

**Comment by danielhuppmann** [comment]
Thanks @sandrinecharousset for raising this issue.

About the first part of the issue - appending/concatenating should work fine even if the two IamDataFrames have different list of years (if these are really just years as integers, see below). I did some tests and cannot replicate this error.

About the second part, you're right, appending/concatenating only works if both IamDataFrames have the same time domain:
- years as integers
- years as integers plus a *subannual* column
- time domain in the datetime format

Will think about how to support this operation...

**Comment by sandrinecharousset** [comment]
@danielhuppmann regarding appending/concatenating should work fine even if the two IamDataFrames have different list of years I cannot any more reproduce the error, so perhaps sth else was wrong.... then first part of issue closed.... Sorry
