### ISSUE TITLE
Renaming empty IamDataFrame returns IndexError

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#631]
Calling the `rename()` method on an empty **IamDataFrame** returns 

```python
IndexError: index 0 is out of bounds for axis 0 with size 0
```
where one could reasonably expect to see an IamDataFrame without raising an error.

Bug reported by @HauHe @Renato-Rodrigues

**Comment by phackstock** [comment]
I was looking at addressing iamconsortium/nomenclature#116 when this error popped up.
@danielhuppmann what should in your opinion be the desired behavior? Should I just return the empty data frame (in case `inplace` is `true`? If so should I log any warning or something along those lines or should I just silently return the empty data frame.
