### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by albertame** [IAMconsortium/pyam#661]
Hi all, 

I am getting the following error: 
SSLError: HTTPSConnectionPool(host='db1.ene.iiasa.ac.at', port=443): Max retries exceeded with url: /EneAuth/config/v1/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

when running: 
pyam.iiasa.Connection('ngfs')

after setting: 
pyam.iiasa.set_config(username, password)

Could you please advice on how to solve it? I was using the connection successfully until March.

Many thanks in advance. 
Kind regards, 
Alberto

**Comment by meksor** [comment]
Hey there, 
our certificates are valid as far as I can see. 
Which operating system are you using?
Can you open  `db1.ene.iiasa.ac.at` in a browser without problems?

cheers

**Comment by albertame** [comment]
Hi, 

Thank you for your swift response. 

Windows 10
this is what I see if I open the mentioned link in a browser: 

Welcome.
To err is human. To really screw up, you need a computer.

Best

**Comment by meksor** [comment]
Yeah, python on windows does apparently not look into the OS' certificate database without having `python-certifi-win32` installed. 
I can't test it right now because im not near a windows computer, but you can try `pip install python-certifi-win32` in the relevant virtualenv. 
Let me know if it works... 
Might be worth considering to add this as a dependency if it does.

**Comment by albertame** [comment]
tried but got the same error. I can confirm that we receive the same error also on Linux machine

**Comment by meksor** [comment]
Ok, let's keep looking then... 
May I ask for the entire code example and the output of `pip freeze`?

**Comment by albertame** [comment]
Code: 
import pyam
pyam.iiasa.set_config(alberto.americo, password**)
pyam.iiasa.Connection('ngfs')

J:\>pip freeze
aiohttp==3.8.1
aiosignal==1.2.0
alabaster==0.7.12
anyio==3.5.0
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.2
astroid==2.5
async-generator==1.10
async-timeout==4.0.2
atomicwrites==1.4.0
attrs==21.4.0
Automat==20.2.0
autopep8==1.6.0
Babel==2.9.1
backcall==0.2.0
bcrypt==3.2.0
beautifulsoup4==4.9.3
binaryornot==0.4.4
black==22.3.0
bleach==4.1.0
bokeh==2.4.2
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.12
click==8.0.4
cloudpickle==2.0.0
colorama==0.4.4
configparser==5.2.0
constantly==15.1.0
cookiecutter==1.7.3
country-converter==0.7.4
coverage==6.3.2
coveralls==3.3.1
cryptography==36.0.1
cycler==0.11.0
debugpy==1.6.0
decorator==5.1.1
defusedxml==0.7.1
diff-match-patch==20200713
distlib==0.3.4
dnspython==2.2.1
docopt==0.6.2
docutils==0.17.1
email-validator==1.1.3
entrypoints==0.4
et-xmlfile==1.1.0
filelock==3.6.0
flake8==4.0.1
frozenlist==1.3.0
future==0.18.2
genson==1.2.2
hyperlink==21.0.0
hypothesis==6.39.4
iam-units==2021.11.12
idna==2.10
imageio==2.9.0
imagesize==1.3.0
importlib-metadata==4.11.3
incremental==21.3.0
inflection==0.5.1
iniconfig==1.1.1
install==1.3.5
intervaltree==3.1.0
ipykernel==6.13.0
ipympl==0.6.3
ipython==7.33.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
isort==5.10.1
jdcal==1.4.1
jedi==0.17.2
jellyfish==0.9.0
Jinja2==3.0.3
jinja2-time==0.2.0
joblib==1.1.0
json5==0.9.6
jsonpickle==2.1.0
jsonschema==4.4.0
jupyter==1.0.0
jupyter-bokeh==2.0.4
jupyter-client==7.1.2
jupyter-console==6.2.0
jupyter-core==4.9.1
jupyter-lsp==1.1.4
jupyter-packaging==0.7.12
jupyter-server==1.4.1
jupyter-server-proxy==1.6.0
jupyter-sphinx==0.3.2
jupyterlab==3.2.8
jupyterlab-launcher==0.13.1
jupyterlab-lsp==3.4.1
jupyterlab-pygments==0.1.2
jupyterlab-server==2.3.0
jupyterlab-widgets==1.0.0
kaleido==0.2.1
keyring==23.5.0
keyrings.cryptfile==1.3.8
kiwisolver==1.3.2
lazy-object-proxy==1.7.1
llvmlite==0.38.0
lxml==4.8.0
Markdown==3.3.4
MarkupSafe==2.0.1
marshmallow==3.10.0
matplotlib==3.3.4
matplotlib-inline==0.1.3
mccabe==0.6.1
medau==0.1.24
medconf==1.0.108
medlr==0.11.0
metakernel==0.27.5
mistune==0.8.4
mock==4.0.3
mpmath==1.2.1
multidict==6.0.2
mypy-extensions==0.4.3
nbclassic==0.2.6
nbclient==0.5.3
nbconvert==6.0.7
nbconvert_reportlab==0.2
nbformat==5.1.2
nest-asyncio==1.5.4
networkx==2.7.1
nltk==3.7
notebook==6.2.0
numba==0.55.1
numpy==1.19.5
numpydoc==1.2
openpyxl==3.0.6
packaging==21.3
pandas==1.3.5
pandas-datareader==0.9.0
pandocfilters==1.5.0
paramiko==2.10.1
parso==0.7.0
pathspec==0.9.0
patsy==0.5.2
pdfrw==0.4
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.2
Pint==0.18
pipdeptree==2.0.0
pkginfo==1.7.0
platformdirs==2.5.1
plotly==5.6.0
pluggy==1.0.0
poyo==0.5.0
prometheus-client==0.13.1
prompt-toolkit==3.0.28
psutil==5.9.0
ptyprocess==0.7.0
py==1.11.0
pyam-iamc==1.4.0
pyaml==21.10.1
pycodestyle==2.8.0
pycparser==2.21
pycryptodome==3.14.1
pydantic==1.9.0
pydocstyle==6.1.1
pyflakes==2.4.0
Pygments==2.11.2
pylint==2.7.1
pyls-black==0.4.7
pyls-spyder==0.4.0
PyNaCl==1.5.0
pyodbc==4.0.32
PyOpenGL==3.1.5
pyOpenSSL==22.0.0
pyparsing==3.0.7
pypiwin32==223
PyQt5==5.12.3
PyQt5-sip==12.9.1
PyQtWebEngine==5.12.1
pyrsistent==0.18.1
pytest==6.2.2
pytest-cov==3.0.0
python-certifi-win32==1.6
python-dateutil==2.8.2
python-dotenv==0.19.2
python-jsonrpc-server==0.4.0
python-language-server==0.36.2
python-lsp-black==1.2.1
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.4.1
python-slugify==6.1.2
pytz==2021.3
PyWavelets==1.3.0
pywin32==303
pywin32-ctypes==0.2.0
pywinpty==2.0.5
PyYAML==6.0
pyzmq==22.3.0
QDarkStyle==3.0.3
qgrid==1.3.1
qstylizer==0.2.1
QtAwesome==1.1.1
qtconsole==5.3.0
QtPy==2.0.1
regex==2022.3.15
reportlab==3.6.8
requests==2.27.1
requests-negotiate-sspi==0.5.2
retrying==1.3.3
rope==0.18.0
Rtree==1.0.0
scikit-fuzzy==0.4.1
scikit-image==0.18.1
scikit-learn==0.24.1
scikit-optimize==0.8.1
scilab2py==0.6.2
scipy==1.8.0
SDMXthon==1.2
seaborn==0.11.2
Send2Trash==1.8.0
setuptools-scm==6.4.2
simpervisor==0.4
simplejson==3.17.2
six==1.16.0
sklearn==0.0
sniffio==1.2.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soupsieve==2.3.1
Sphinx==4.4.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
spyder==5.3.0
spyder-kernels==2.3.0
stata-setup==0.1.2
statsmodels==0.13.2
tabpy==2.5.0
tenacity==8.0.1
terminado==0.13.3
testpath==0.6.0
text-unidecode==1.3
textblob==0.17.1
textdistance==4.2.2
threadpoolctl==3.1.0
three-merge==0.1.1
tifffile==2022.2.9
timedisagg==0.0.1
tinycss2==1.1.1
toml==0.10.2
tomli==2.0.1
tomli_w==1.0.0
tornado==6.1
tqdm==4.63.1
traitlets==5.1.1
Twisted==22.2.0
twisted-iocpsupport==1.0.2
typing_extensions==4.1.1
ujson==5.1.0
urllib3==1.26.8
validators==0.18.2
virtualenv==20.4.2
virtualenvwrapper-win==1.2.6
watchdog==1.0.2
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
wrapt==1.12.1
xlrd==2.0.1
XlsxWriter==1.3.7
xmltodict==0.12.0
yapf==0.32.0
yarl==1.7.2
zipp==3.7.0
zope.interface==5.4.0

**Comment by meksor** [comment]
I cannot reproduce the issue at all on my machine. 
I suspect it is not an issue with pyam, so I would continue this on another medium.

**Comment by danielhuppmann** [comment]
Sorry @albertame, seems that this is not a problem with pyam or the IIASA database infrastructure. Please try from a different network (maybe a firewall issue?) and/or a different computer. If the problem persists, please reach out to me at <lastname>@iiasa.ac.at.
