### ISSUE TITLE
Trouble with request: {"statusCode":401,"errorCode":"TOKEN_INVALID","errorMessage":"JWT auth failed, reason: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted."}

### ISSUE THREAD

**Issue by shiladitya146** [IAMconsortium/pyam#672]
Hi I am getting the following error on running this code:
df = pyam.read_iiasa('iamc15')df = pyam.read_iiasa('iamc15')

**Comment by danielhuppmann** [comment]
We recently migrated this instance to a new authentication and user-management service. Please reset your password at https://manager.ece.iiasa.ac.at/, then save the new password to your machine as described in the docs: https://pyam-iamc.readthedocs.io/en/stable/api/iiasa.html#pyam.iiasa.set_config

If this does not solve the problem, please restart your computer.

**Comment by danielhuppmann** [comment]
@meksor identified an issue with the token-timeout in the IIASA authentication system yesterday and implemented a fix. Please try again.

**Comment by danielhuppmann** [comment]
Can you please try again and let us know if the problem still exists?

**Comment by danielhuppmann** [comment]
Closing as no response for >1 month. Please reopen if the issue persists or reappears.
