### ISSUE TITLE
Support adding dataframes of metadata

### ISSUE THREAD

**Issue by gidden** [IAMconsortium/pyam#678]
At present, one must either add metadata from a file (`load_meta()`) or individually (`set_meta()`). We can extend one of these (probably best to do so on `set_meta()`) to support loading multiple metadata columns in one go. 

Does anyone have an opinion before I propose an implementation?

cc @danielhuppmann

**Comment by danielhuppmann** [comment]
Sure, good idea! For completeness, you can already pass a suitable **pd.DataFrame** at initialization using
```python
pyam.DataFrame(data, meta=<some meta frame>)
```

This is implemented here, should be just a few lines (and a test) to extend `set_meta()`
https://github.com/IAMconsortium/pyam/blob/1abb9784c7bb79cc3701deb5161fa20c1899d2ae/pyam/core.py#L206

**Comment by gidden** [comment]
closed by #679
