### ISSUE TITLE
Invalid properties of AR6 database

### ISSUE THREAD

**Issue by Rlamboll** [IAMconsortium/pyam#693]
Running `pyam.iiasa.Connection("ar6-public").properties()`
produces "ValueError: Protocol not known: [<lots of info>]", rather than returning a sensible set of info.

**Comment by danielhuppmann** [comment]
If you are using the latest from GitHub, maybe you didn’t install 

> httpx[http2]

which was added as a requirement?

https://github.com/IAMconsortium/pyam/blob/e7f0c3a2e8ba618e1b621333064657e38db898c4/setup.cfg#L33

**Comment by Rlamboll** [comment]
You're right that I hadn't installed them (and also needed to install fsspc to get anything sensible at all) but doing so doesn't seem to resolve this problem. It works fine for iamc15 with or without httpx[http2].

**Comment by danielhuppmann** [comment]
I cannot replicate this error, having tried version 1.5 and the latest from GitHub as well as registered vs. anonymous login. Please provide more details on the issue.

**Comment by Rlamboll** [comment]
I've done a clean install of everything on a fresh env and this problem now doesn't occur for ar6, so presumably it's some weird version incompatibility. However the database netzero2040 doesn't seem to return a valid properties in either environment.

**Comment by danielhuppmann** [comment]
The netzero2040 database does not (yet) have any scenarios, so this is a remainder of an issue when the returned data is empty. Should have been fixed with #691, but wasn't...

**Comment by Rlamboll** [comment]
Thanks, I think this doesn't need a new issue if that's an already-established bug
