### ISSUE TITLE
Reading filtered dataframes from iiasa contain incorrect properties

### ISSUE THREAD

**Issue by Rlamboll** [IAMconsortium/pyam#694]
When reading from the IIASA database, the returned database seems to always have .model, .scenario and .variable properties of the unfiltered database, even when we request only a subset of data. 

`new_read = read_iiasa(
        "iamc15", scenario="SSP2*", model="MESSAGE*", variable="*CO2" 
 )
print(new_read.scenario)
print(new_read.variable)`
investigate the properties

**Comment by danielhuppmann** [comment]
Interesting. From a first glance, the culprit is not the IIASA database API but initializing an **IamDataFrame** with incompatible *data* and *meta* indices...
