### ISSUE TITLE
Remove support of `xls` files 

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#706]
Following on a discussion with @Rlamboll, I did some tests and noticed that writing to and reading from `xls` does currently not work as expected:
- reading ignores the "meta" sheet
- writing always uses xlsx-filetype even if the file name is .xls (or anything else)

Given that `xls` is now superseded by `xlsx` for quite a while, I suggest to vote on whether to explicitly remove xsl support.
- :thumbsup: - let's remove it
- :thumbsdown: - better to keep it (and try to fix support for it)

@gidden @jkikstra @znicholls @phackstock

**Comment by phackstock** [comment]
Considering it's been quite a while now that `xlsx` has been around I would say it's fair to streamline and drop the support.

**Comment by danielhuppmann** [comment]
Thank you for double-checking with the climate-assessment package!
