### ISSUE TITLE
users changing data which are in the meta index should also update that index

### ISSUE THREAD

**Issue by gidden** [IAMconsortium/pyam#74]
For example, if one does

```
df['scenario'] = df['scenario'].apply(lambda x: x[:-len('-V25')])
```

this change should also be applied to values in the metadata index.

should be something like

```
    def __setitem__(self, key, value):
        if key in self.meta.index:
              mapping = dict(zip(self.data[key], value))
              # do metadata set as well
        return self.__setitem__(key, value)
```

**Comment by danielhuppmann** [comment]
The first use case is now covered by `df.rename({'scenario': {'old_name': 'new_name'})`.

The bigger question is whether a user should make changes directly to `data` or `meta`.

**Comment by gidden** [comment]
*probably* not. We should probably make those private (_data, _meta) and
have access restricted to methods.

**Comment by danielhuppmann** [comment]
@gidden, can we close this issue or is there still something that should be done (with reasonable priority)?

**Comment by gidden** [comment]
Agreed!
