### ISSUE TITLE
Unable to load .csv data

### ISSUE THREAD

**Issue by majaheim** [IAMconsortium/pyam#741]
Loading .csv data does not seem to work. I reveice the following error messages: 

![grafik](https://github.com/IAMconsortium/pyam/assets/124357819/c451b475-4ff0-4772-99a8-c7f7528cae05)

![grafik](https://github.com/IAMconsortium/pyam/assets/124357819/47cbc352-ed15-436c-9685-d02dbd5f66b3)

When loading .xlsx files everything works just fine.

**Comment by danielhuppmann** [comment]
Thank you for reporting this issue @majaheim! FWIW, this is not a pyam bug, but a specific warning about an incompatible file. In any case, simply removing the line starting with "©" should do the trick...
