### ISSUE TITLE
Refactor the "exclude" feature

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#755]
All validation methods have a flag "exclude_on_fail" feature to easily track which scenarios fail one or several validation steps. This is implemented via an "exclude" column in the meta indicators.

However, this approach causes some hiccups in the integration with the ixmp database infrastructure - the "exclude" meta indicator is always added by pyam and then has to be removed before importing to the database (or can cause confusion by users).

My proposal: drop the "exclude" column from the "meta" dataframe and move it to an own attribute. in addition, extend the `filter()` method such that `df.filter(exclude=True)` continues to work as is.

Any thoughts @phackstock @gidden @byersiiasa?

**Comment by byersiiasa** [comment]
Sure - sounds fine to me.
But would there be a method to edit the exclude attribute manually? 
e.g., perhaps similar to how one might use set_meta('exclude'...)
