### ISSUE TITLE
Algebraic operations on timeseries data between scenarios

### ISSUE THREAD

**Issue by cheolhung** [IAMconsortium/pyam#760]
How do algebraic operations between scenarios with a IamDataFrame?
For example, If I want to calculate the difference of primary energy between Scenario A and Scenario B,  and append a new timeseries with a new scenario name in the frame, Is there any function to do it easily? (I couldn't find any help from pyam webpage)

Thanks in advance.   

![image](https://github.com/IAMconsortium/pyam/assets/11956390/2a0834d9-6797-4d20-8a47-431ca263a4b6)

**Comment by danielhuppmann** [comment]
You can use the `axis` keyword-argument of the [`subtract()`](https://pyam-iamc.readthedocs.io/en/stable/api/iamdataframe.html#pyam.IamDataFrame.subtract) method (or `divide()` if you want to have the relative difference). See the tutorial notebook at https://github.com/danielhuppmann/ENGAGE-pyam-tutorial/ for an example.

Please close this issue if this answer was sufficient, or let me know if you need more help.

**Comment by cheolhung** [comment]
Thanks a million!

**Comment by cheolhung** [comment]
I have another issue with algebraic operations.
If I use 'append=True', there is an error such as 'ValueError: Timeseries data has overlapping values:'
Would you please help me fix it?
Thanks in advance.

![image](https://github.com/IAMconsortium/pyam/assets/11956390/428ccb55-4b14-43a9-893c-9c58c17807d5)

**Comment by danielhuppmann** [comment]
My guess is that you have executed this cell twice - so you already appended the date, and then try to append it again. To which pyam (rightly) raises an error that there is overlapping (duplicate) data between the already data in `df` and the to-be-appended data.

**Comment by cheolhung** [comment]
I thought the error occurred when I executed the first time. Now I see that the to-be-appended data is already in the data frame.
I really appreciate your prompt reply.
