### ISSUE TITLE
Remove region-mappings from pyam core

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/pyam#765]
The pyam directory contains a region-mapping csv from some long-ago project.

Given that this functionality is now superseded by the nomenclature package and the common-definitions repo (see [here](https://github.com/IAMconsortium/common-definitions/blob/main/definitions/region/common.yaml)), I suggest to remove the region-mapping from the pyam source code.

Any objections @gidden? Anyone else who ever used this?

**Comment by phackstock** [comment]
From what I recall @fabiosferra uses this in his downscaling algorithm. But I could be wrong.

**Comment by fabiosferra** [comment]
Yes, the downscaling algorithm uses a `default_mapping.csv`  file that (initially) came from Pyam.  However now I am using a script that creates this file directly from the IAMs model_registration files. Therefore, no objections from my side.
