### ISSUE TITLE
Pyam does currently not support 3.12

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/pyam#798]
It's been a little over a month since python 3.12 was officially released. 
Would be worth a short to see if it's out of the box compatible if that hasn't been tested so far.

**Comment by danielhuppmann** [comment]
I can tell you at least one dependency that is not yet released for Python 3.12… https://github.com/iiasa/ixmp4

**Comment by phackstock** [comment]
Ah right, then we'll have to revisit this at some point. I'd keep this issue open though.

**Comment by glatterf42** [comment]
ixmp4 is out now: https://pypi.org/project/ixmp4/ :)
So please check if pyam now supports 3.12 and if it does, please do another release without the version pin :)

**Comment by glatterf42** [comment]
Closed via #825.
