### ISSUE TITLE
'stable' docs missing gallery

### ISSUE THREAD

**Issue by EFord36** [IAMconsortium/pyam#803]
Hi,

I was browsing the readme for this project, and noticed the links for the plotting gallery were broken - they give me a 404 when I go to: https://pyam-iamc.readthedocs.io/en/stable/gallery/index.html

However, I noticed that for the 'latest' docs, the link works fine: https://pyam-iamc.readthedocs.io/en/latest/gallery/index.html

Digging a little bit, it looks like there was a problem that caused the gallery to disappear from the docs that got fixed here: https://github.com/IAMconsortium/pyam/pull/784 . But this is after the last release (v2.0.0), so currently the 'stable' docs don't have the gallery.

It looks like the easiest fix is a new release, not sure if that's something you want at the moment though. Thought I would open an issue so that you're aware!

**Comment by danielhuppmann** [comment]
Thanks for this issue, we'll do another release soon!
 (I fixed a wrong link in the issue description).

**Comment by danielhuppmann** [comment]
We made a new release today and the plotting gallery is now correctly shown again on the stable docs.
