### ISSUE TITLE
Migrating to Poetry for project management

### ISSUE THREAD

**Issue by glatterf42** [IAMconsortium/pyam#823]
Since @danielhuppmann just brought it up: is there interest in migrating this project to [Poetry](https://python-poetry.org/docs/)? Personally, I'd also like to try out [Rye](https://rye-up.com/) even though it's new. 

If either case is true, I can set up a PR to play around with.

**Comment by danielhuppmann** [comment]
I'd be happy if you try migrating to poetry. Not sure if it's a good idea to try Rye on this package, as it's already quite large - maybe a smaller project may be a better guinea pig.

**Comment by phackstock** [comment]
I'd hard veto rye, at least for the moment. To me there's nothing obvious wrong with poetry and I don't want to switch for the sake of switching. 
Unless you have a good argument for a killer feature of rye.
