### ISSUE TITLE
how to install pyam

### ISSUE THREAD

**Issue by AZFARHAD24511** [IAMconsortium/pyam#852]
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Admin\miniconda3\Lib\site-packages\pyam\__init__.py", line 9, in <module>
    from . initial_guesses import OrthogonalPolynomialInitialGuess
  File "C:\Users\Admin\miniconda3\Lib\site-packages\pyam\initial_guesses.py", line 10, in <module>
    import pycollocation
ModuleNotFoundError: No module named 'pycollocation'

(base) C:\Users\Admin>conda install -c conda-forge pyam
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Admin\miniconda3

  added / updated specs:
    - pyam

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    alembic-1.13.1             |     pyhd8ed1ab_1         155 KB  conda-forge
    annotated-types-0.6.0      |     pyhd8ed1ab_0          17 KB  conda-forge
    brotli-1.1.0               |       hcfcfb64_1          19 KB  conda-forge
    brotli-bin-1.1.0           |       hcfcfb64_1          20 KB  conda-forge
    ca-certificates-2024.2.2   |       h56e8100_0         152 KB  conda-forge
    certifi-2024.2.2           |     pyhd8ed1ab_0         157 KB  conda-forge
    colour-0.1.5               |     pyhd8ed1ab_1          21 KB  conda-forge
    conda-23.11.0              |  py311h1ea47a8_1         1.2 MB  conda-forge
    contourpy-1.2.1            |  py311h005e61a_0         202 KB  conda-forge
    cycler-0.12.1              |     pyhd8ed1ab_0          13 KB  conda-forge
    et_xmlfile-1.1.0           |     pyhd8ed1ab_0          10 KB  conda-forge
    fastapi-0.103.0            |     pyhd8ed1ab_0          55 KB  conda-forge
    furl-2.1.3                 |     pyhd8ed1ab_0          22 KB  conda-forge
    glib-2.78.4                |       hd77b12b_0         491 KB
    glib-tools-2.78.4          |       hd77b12b_0          91 KB
    greenlet-3.0.3             |  py311h12c1d0e_0         217 KB  conda-forge
    gstreamer-1.18.5           |       hdff456e_3         2.1 MB  conda-forge
    h11-0.14.0                 |     pyhd8ed1ab_0          47 KB  conda-forge
    h2-4.1.0                   |     pyhd8ed1ab_0          46 KB  conda-forge
    hpack-4.0.0                |     pyh9f0ad1d_0          25 KB  conda-forge
    httpcore-1.0.5             |     pyhd8ed1ab_0          45 KB  conda-forge
    httpx-0.27.0               |     pyhd8ed1ab_0          63 KB  conda-forge
    hyperframe-6.0.1           |     pyhd8ed1ab_0          14 KB  conda-forge
    iam-units-2023.9.12        |     pyhd8ed1ab_0          37 KB  conda-forge
    importlib_resources-6.4.0  |     pyhd8ed1ab_0          32 KB  conda-forge
    infinity-1.5               |     pyhd8ed1ab_0           7 KB  conda-forge
    intervals-0.9.2            |     pyhd8ed1ab_0          11 KB  conda-forge
    ixmp4-0.8.3                |     pyhd8ed1ab_0          92 KB  conda-forge
    jbig-2.1                   |    h8d14728_2003          45 KB  conda-forge
    kiwisolver-1.4.5           |  py311h005e61a_1          55 KB  conda-forge
    krb5-1.21.2                |       heb0366b_0         694 KB  conda-forge
    lerc-2.2.1                 |       h0e60522_0         133 KB  conda-forge
    libblas-3.9.0              |1_h8933c1f_netlib         193 KB  conda-forge
    libbrotlicommon-1.1.0      |       hcfcfb64_1          69 KB  conda-forge
    libbrotlidec-1.1.0         |       hcfcfb64_1          32 KB  conda-forge
    libbrotlienc-1.1.0         |       hcfcfb64_1         241 KB  conda-forge
    libcblas-3.9.0             |5_hd5c7e75_netlib          95 KB  conda-forge
    libdeflate-1.7             |       h8ffe710_5          61 KB  conda-forge
    libglib-2.78.4             |       ha17d25a_0         1.3 MB
    libogg-1.3.4               |       h8ffe710_1          34 KB  conda-forge
    libtiff-4.3.0              |       h0c97f57_1         1.1 MB  conda-forge
    libvorbis-1.3.7            |       h0e60522_0         267 KB  conda-forge
    libwebp-base-1.4.0         |       hcfcfb64_0         268 KB  conda-forge
    m2w64-gcc-libgfortran-5.3.0|                6         342 KB  conda-forge
    m2w64-gcc-libs-5.3.0       |                7         520 KB  conda-forge
    m2w64-gcc-libs-core-5.3.0  |                7         214 KB  conda-forge
    m2w64-gmp-6.1.0            |                2         726 KB  conda-forge
    m2w64-libwinpthread-git-5.0.0.4634.697f757|                2          31 KB  conda-forge
    mako-1.3.3                 |     pyhd8ed1ab_0          65 KB  conda-forge
    msys2-conda-epoch-20160418 |                1           3 KB  conda-forge
    multimethod-1.9.1          |     pyhd8ed1ab_0          14 KB  conda-forge
    munkres-1.1.4              |     pyh9f0ad1d_0          12 KB  conda-forge
    openjpeg-2.4.0             |       hb211442_1         238 KB  conda-forge
    openpyxl-3.1.2             |  py311ha68e1ae_1         635 KB  conda-forge
    orderedmultidict-1.0.1     |     pyhd8ed1ab_1          16 KB  conda-forge
    pandera-0.18.3             |       hd8ed1ab_0           7 KB  conda-forge
    pandera-base-0.18.3        |     pyhd8ed1ab_0         125 KB  conda-forge
    passlib-1.7.4              |     pyhd8ed1ab_1         378 KB  conda-forge
    patsy-0.5.6                |     pyhd8ed1ab_0         183 KB  conda-forge
    pendulum-3.0.0             |  py311h633b200_0         349 KB  conda-forge
    phonenumbers-8.13.35       |     pyhd8ed1ab_0         1.4 MB  conda-forge
    pillow-10.2.0              |  py311h2bbff1b_0         953 KB
    pint-0.23                  |     pyhd8ed1ab_0         232 KB  conda-forge
    pluggy-1.5.0               |     pyhd8ed1ab_0          23 KB  conda-forge
    psycopg-3.1.18             |  py311h9e3867f_0         381 KB  conda-forge
    psycopg-c-3.1.18           |  py311h89d7736_0         267 KB  conda-forge
    pyam-2.2.2                 |     pyhd8ed1ab_0          81 KB  conda-forge
    pydantic-2.7.1             |     pyhd8ed1ab_0         276 KB  conda-forge
    pydantic-settings-2.2.1    |     pyhd8ed1ab_0          18 KB  conda-forge
    pyjwt-2.8.0                |     pyhd8ed1ab_1          24 KB  conda-forge
    pyparsing-3.1.2            |     pyhd8ed1ab_0          87 KB  conda-forge
    python-dotenv-1.0.1        |     pyhd8ed1ab_0          24 KB  conda-forge
    qt-main-5.15.2             |       he8e5bd7_7        50.0 MB
    rich-13.7.1                |     pyhd8ed1ab_0         180 KB  conda-forge
    seaborn-0.13.2             |       hd8ed1ab_0           7 KB  conda-forge
    seaborn-base-0.13.2        |     pyhd8ed1ab_0         229 KB  conda-forge
    shellingham-1.5.4          |     pyhd8ed1ab_0          14 KB  conda-forge
    sqlalchemy-utils-0.41.2    |     pyhd8ed1ab_0           7 KB  conda-forge
    sqlalchemy-utils-arrow-0.41.2|     pyhd8ed1ab_0           7 KB  conda-forge
    sqlalchemy-utils-babel-0.41.2|     pyhd8ed1ab_0           7 KB  conda-forge
    sqlalchemy-utils-base-0.41.2|     pyhd8ed1ab_0          68 KB  conda-forge
    sqlalchemy-utils-color-0.41.2|     pyhd8ed1ab_0           7 KB  conda-forge
    sqlalchemy-utils-encrypted-0.41.2|     pyhd8ed1ab_0           7 KB  conda-forge
    sqlalchemy-utils-intervals-0.41.2|     pyhd8ed1ab_0           7 KB  conda-forge
    sqlalchemy-utils-password-0.41.2|     pyhd8ed1ab_0           7 KB  conda-forge
    sqlalchemy-utils-pendulum-0.41.2|     pyhd8ed1ab_0           7 KB  conda-forge
    sqlalchemy-utils-phone-0.41.2|     pyhd8ed1ab_0           7 KB  conda-forge
    sqlalchemy-utils-timezone-0.41.2|     pyhd8ed1ab_0           7 KB  conda-forge
    sqlalchemy-utils-url-0.41.2|     pyhd8ed1ab_0           7 KB  conda-forge
    starlette-0.27.0           |     pyhd8ed1ab_0          54 KB  conda-forge
    time-machine-2.14.1        |  py311ha68e1ae_0          39 KB  conda-forge
    toml-0.10.2                |     pyhd8ed1ab_0          18 KB  conda-forge
    typeguard-4.2.1            |     pyhd8ed1ab_0          33 KB  conda-forge
    typer-0.12.3               |     pyhd8ed1ab_0          51 KB  conda-forge
    typer-slim-0.12.3          |     pyhd8ed1ab_0          45 KB  conda-forge
    typer-slim-standard-0.12.3 |       hd8ed1ab_0          45 KB  conda-forge
    typing_inspect-0.9.0       |     pyhd8ed1ab_0          15 KB  conda-forge
    ucrt-10.0.22621.0          |       h57928b3_0         1.2 MB  conda-forge
    vc14_runtime-14.38.33130   |      h82b7239_18         732 KB  conda-forge
    vs2015_runtime-14.38.33130 |      hcb4865c_18          17 KB  conda-forge
    wquantiles-0.6             |     pyhd8ed1ab_0           8 KB  conda-forge
    xlsxwriter-3.1.9           |     pyhd8ed1ab_0         118 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        70.3 MB

The following NEW packages will be INSTALLED:

  alembic            conda-forge/noarch::alembic-1.13.1-pyhd8ed1ab_1
  annotated-types    conda-forge/noarch::annotated-types-0.6.0-pyhd8ed1ab_0
  brotli             conda-forge/win-64::brotli-1.1.0-hcfcfb64_1
  brotli-bin         conda-forge/win-64::brotli-bin-1.1.0-hcfcfb64_1
  colour             conda-forge/noarch::colour-0.1.5-pyhd8ed1ab_1
  contourpy          conda-forge/win-64::contourpy-1.2.1-py311h005e61a_0
  cycler             conda-forge/noarch::cycler-0.12.1-pyhd8ed1ab_0
  et_xmlfile         conda-forge/noarch::et_xmlfile-1.1.0-pyhd8ed1ab_0
  fastapi            conda-forge/noarch::fastapi-0.103.0-pyhd8ed1ab_0
  fonttools          conda-forge/win-64::fonttools-4.51.0-py311ha68e1ae_0
  furl               conda-forge/noarch::furl-2.1.3-pyhd8ed1ab_0
  gettext            conda-forge/win-64::gettext-0.19.8.1-ha2e2712_1008
  glib               pkgs/main/win-64::glib-2.78.4-hd77b12b_0
  glib-tools         pkgs/main/win-64::glib-tools-2.78.4-hd77b12b_0
  greenlet           conda-forge/win-64::greenlet-3.0.3-py311h12c1d0e_0
  gst-plugins-base   conda-forge/win-64::gst-plugins-base-1.18.5-he07aa86_0
  gstreamer          conda-forge/win-64::gstreamer-1.18.5-hdff456e_3
  h11                conda-forge/noarch::h11-0.14.0-pyhd8ed1ab_0
  h2                 conda-forge/noarch::h2-4.1.0-pyhd8ed1ab_0
  hpack              conda-forge/noarch::hpack-4.0.0-pyh9f0ad1d_0
  httpcore           conda-forge/noarch::httpcore-1.0.5-pyhd8ed1ab_0
  httpx              conda-forge/noarch::httpx-0.27.0-pyhd8ed1ab_0
  hyperframe         conda-forge/noarch::hyperframe-6.0.1-pyhd8ed1ab_0
  iam-units          conda-forge/noarch::iam-units-2023.9.12-pyhd8ed1ab_0
  importlib_resourc~ conda-forge/noarch::importlib_resources-6.4.0-pyhd8ed1ab_0
  infinity           conda-forge/noarch::infinity-1.5-pyhd8ed1ab_0
  intervals          conda-forge/noarch::intervals-0.9.2-pyhd8ed1ab_0
  ixmp4              conda-forge/noarch::ixmp4-0.8.3-pyhd8ed1ab_0
  jbig               conda-forge/win-64::jbig-2.1-h8d14728_2003
  kiwisolver         conda-forge/win-64::kiwisolver-1.4.5-py311h005e61a_1
  lerc               conda-forge/win-64::lerc-2.2.1-h0e60522_0
  libblas            conda-forge/win-64::libblas-3.9.0-1_h8933c1f_netlib
  libbrotlicommon    conda-forge/win-64::libbrotlicommon-1.1.0-hcfcfb64_1
  libbrotlidec       conda-forge/win-64::libbrotlidec-1.1.0-hcfcfb64_1
  libbrotlienc       conda-forge/win-64::libbrotlienc-1.1.0-hcfcfb64_1
  libcblas           conda-forge/win-64::libcblas-3.9.0-5_hd5c7e75_netlib
  libdeflate         conda-forge/win-64::libdeflate-1.7-h8ffe710_5
  libglib            pkgs/main/win-64::libglib-2.78.4-ha17d25a_0
  liblapack          conda-forge/win-64::liblapack-3.9.0-5_hd5c7e75_netlib
  libogg             conda-forge/win-64::libogg-1.3.4-h8ffe710_1
  libtiff            conda-forge/win-64::libtiff-4.3.0-h0c97f57_1
  libvorbis          conda-forge/win-64::libvorbis-1.3.7-h0e60522_0
  libwebp-base       conda-forge/win-64::libwebp-base-1.4.0-hcfcfb64_0
  m2w64-gcc-libgfor~ conda-forge/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     conda-forge/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ conda-forge/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          conda-forge/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ conda-forge/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  mako               conda-forge/noarch::mako-1.3.3-pyhd8ed1ab_0
  matplotlib-base    conda-forge/win-64::matplotlib-base-3.8.4-py311h6e989c2_0
  msys2-conda-epoch  conda-forge/win-64::msys2-conda-epoch-20160418-1
  multimethod        conda-forge/noarch::multimethod-1.9.1-pyhd8ed1ab_0
  munkres            conda-forge/noarch::munkres-1.1.4-pyh9f0ad1d_0
  openjpeg           conda-forge/win-64::openjpeg-2.4.0-hb211442_1
  openpyxl           conda-forge/win-64::openpyxl-3.1.2-py311ha68e1ae_1
  orderedmultidict   conda-forge/noarch::orderedmultidict-1.0.1-pyhd8ed1ab_1
  pandas             conda-forge/win-64::pandas-2.2.2-py311hf63dbb6_0
  pandera            conda-forge/noarch::pandera-0.18.3-hd8ed1ab_0
  pandera-base       conda-forge/noarch::pandera-base-0.18.3-pyhd8ed1ab_0
  passlib            conda-forge/noarch::passlib-1.7.4-pyhd8ed1ab_1
  patsy              conda-forge/noarch::patsy-0.5.6-pyhd8ed1ab_0
  pendulum           conda-forge/win-64::pendulum-3.0.0-py311h633b200_0
  phonenumbers       conda-forge/noarch::phonenumbers-8.13.35-pyhd8ed1ab_0
  pillow             pkgs/main/win-64::pillow-10.2.0-py311h2bbff1b_0
  pint               conda-forge/noarch::pint-0.23-pyhd8ed1ab_0
  pluggy             conda-forge/noarch::pluggy-1.5.0-pyhd8ed1ab_0
  psycopg            conda-forge/win-64::psycopg-3.1.18-py311h9e3867f_0
  psycopg-c          conda-forge/win-64::psycopg-c-3.1.18-py311h89d7736_0
  pyam               conda-forge/noarch::pyam-2.2.2-pyhd8ed1ab_0
  pydantic           conda-forge/noarch::pydantic-2.7.1-pyhd8ed1ab_0
  pydantic-core      conda-forge/win-64::pydantic-core-2.18.2-py311h533ab2d_0
  pydantic-settings  conda-forge/noarch::pydantic-settings-2.2.1-pyhd8ed1ab_0
  pyjwt              conda-forge/noarch::pyjwt-2.8.0-pyhd8ed1ab_1
  pyparsing          conda-forge/noarch::pyparsing-3.1.2-pyhd8ed1ab_0
  python-dotenv      conda-forge/noarch::python-dotenv-1.0.1-pyhd8ed1ab_0
  python_abi         conda-forge/win-64::python_abi-3.11-2_cp311
  scipy              conda-forge/win-64::scipy-1.13.0-py311h0b4df5a_0
  seaborn            conda-forge/noarch::seaborn-0.13.2-hd8ed1ab_0
  seaborn-base       conda-forge/noarch::seaborn-base-0.13.2-pyhd8ed1ab_0
  shellingham        conda-forge/noarch::shellingham-1.5.4-pyhd8ed1ab_0
  sqlalchemy         conda-forge/win-64::sqlalchemy-2.0.29-py311ha68e1ae_0
  sqlalchemy-utils   conda-forge/noarch::sqlalchemy-utils-0.41.2-pyhd8ed1ab_0
  sqlalchemy-utils-~ conda-forge/noarch::sqlalchemy-utils-arrow-0.41.2-pyhd8ed1ab_0
  sqlalchemy-utils-~ conda-forge/noarch::sqlalchemy-utils-babel-0.41.2-pyhd8ed1ab_0
  sqlalchemy-utils-~ conda-forge/noarch::sqlalchemy-utils-base-0.41.2-pyhd8ed1ab_0
  sqlalchemy-utils-~ conda-forge/noarch::sqlalchemy-utils-color-0.41.2-pyhd8ed1ab_0
  sqlalchemy-utils-~ conda-forge/noarch::sqlalchemy-utils-encrypted-0.41.2-pyhd8ed1ab_0
  sqlalchemy-utils-~ conda-forge/noarch::sqlalchemy-utils-intervals-0.41.2-pyhd8ed1ab_0
  sqlalchemy-utils-~ conda-forge/noarch::sqlalchemy-utils-password-0.41.2-pyhd8ed1ab_0
  sqlalchemy-utils-~ conda-forge/noarch::sqlalchemy-utils-pendulum-0.41.2-pyhd8ed1ab_0
  sqlalchemy-utils-~ conda-forge/noarch::sqlalchemy-utils-phone-0.41.2-pyhd8ed1ab_0
  sqlalchemy-utils-~ conda-forge/noarch::sqlalchemy-utils-timezone-0.41.2-pyhd8ed1ab_0
  sqlalchemy-utils-~ conda-forge/noarch::sqlalchemy-utils-url-0.41.2-pyhd8ed1ab_0
  starlette          conda-forge/noarch::starlette-0.27.0-pyhd8ed1ab_0
  statsmodels        conda-forge/win-64::statsmodels-0.14.1-py311h59ca53f_0
  time-machine       conda-forge/win-64::time-machine-2.14.1-py311ha68e1ae_0
  toml               conda-forge/noarch::toml-0.10.2-pyhd8ed1ab_0
  typeguard          conda-forge/noarch::typeguard-4.2.1-pyhd8ed1ab_0
  typer              conda-forge/noarch::typer-0.12.3-pyhd8ed1ab_0
  typer-slim         conda-forge/noarch::typer-slim-0.12.3-pyhd8ed1ab_0
  typer-slim-standa~ conda-forge/noarch::typer-slim-standard-0.12.3-hd8ed1ab_0
  typing_inspect     conda-forge/noarch::typing_inspect-0.9.0-pyhd8ed1ab_0
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0
  vc14_runtime       conda-forge/win-64::vc14_runtime-14.38.33130-h82b7239_18
  wquantiles         conda-forge/noarch::wquantiles-0.6-pyhd8ed1ab_0
  xlsxwriter         conda-forge/noarch::xlsxwriter-3.1.9-pyhd8ed1ab_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2023.12.12~ --> conda-forge::ca-certificates-2024.2.2-h56e8100_0
  conda              pkgs/main::conda-23.11.0-py311haa9553~ --> conda-forge::conda-23.11.0-py311h1ea47a8_1
  krb5                    pkgs/main::krb5-1.20.1-h5b6d351_0 --> conda-forge::krb5-1.21.2-heb0366b_0
  libpq                   pkgs/main::libpq-12.15-h906ac69_1 --> conda-forge::libpq-16.2-hdb24f17_1
  openssl              pkgs/main::openssl-3.0.13-h2bbff1b_0 --> conda-forge::openssl-3.2.1-hcfcfb64_1
  rich               pkgs/main/win-64::rich-13.3.5-py311ha~ --> conda-forge/noarch::rich-13.7.1-pyhd8ed1ab_0
  vs2015_runtime     pkgs/main::vs2015_runtime-14.27.29016~ --> conda-forge::vs2015_runtime-14.38.33130-hcb4865c_18

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            pkgs/main/win-64::certifi-2024.2.2-py~ --> conda-forge/noarch::certifi-2024.2.2-pyhd8ed1ab_0
  libclang           pkgs/main::libclang-14.0.6-default_hb~ --> conda-forge::libclang-12.0.1-default_h81446c8_4

The following packages will be DOWNGRADED:

  icu                                       73.1-h6c2663c_0 --> 58.2-ha925a31_3
  qt-main                                5.15.2-h19c9488_10 --> 5.15.2-he8e5bd7_7

Proceed ([y]/n)? y

Downloading and Extracting Packages:

[Errno 36] Resource deadlock avoided
[Errno 36] Resource deadlock avoided

**Comment by danielhuppmann** [comment]
Could it be that you first tried to install **pyam** using `pip`, then tried via `conda`?

It seems that the conda-install failed given the last line
> `[Errno 36] Resource deadlock avoided`

Please try to install via pip using the correct package name on pypi.org, 
```
pip install pyam-iamc
```

as described at https://pyam-iamc.readthedocs.io/en/stable/install.html.

I apologize for the inconvenience with the divergent package names on conda vs. pipy.

**Comment by danielhuppmann** [comment]
Closing as no further comment, please reopen if still relevant
