### ISSUE TITLE
read_iiasa() - run too long when ignoring 'variable'

### ISSUE THREAD

**Issue by zhurongqi** [IAMconsortium/pyam#855]
I want to load all model-scenarios in "ar6-public" when ignoring `variable`, but it seems to run for a long time.
What should I do to solve it? Thanks a lot.
![image](https://github.com/IAMconsortium/pyam/assets/52625784/185a078d-e462-4009-ab44-b1d8a5cebc4f)

**Comment by danielhuppmann** [comment]
For large queries, it‘s better to download the file from the AR6 Scenario Explorer. Or you get the list of model-scenario combinations using 
```
conn = pyam.iiasa.Connection(“ar6-public”)
scenario_list = conn.properties()
```
and then iterate over the individual model-scenario combinations.

**Comment by zhurongqi** [comment]
> For large queries, it‘s better to download the file from the AR6 Scenario Explorer. Or you get the list of model-scenario combinations using
> 
> ```
> conn = pyam.iiasa.Connection(“ar6-public”)
> scenario_list = conn.properties()
> ```
> 
> and then iterate over the individual model-scenario combinations.

Thanks @danielhuppmann, I got the initial IamDataFrame from your method, and I will continue to work on it.
`conn = pyam.iiasa.Connection(“ar6-public”)
scenario_list = conn.properties()`
