### ISSUE TITLE
Question: How to connect as a guest when i already have stored credientials?

### ISSUE THREAD

**Issue by lindnemi** [IAMconsortium/pyam#863]
I have project internal login data for the `ariadne` database stored via `ixmp4 login`. Now, i would like to connect to that same database, but as a guest user, to see which data is publicly available. It works via the web interface, but i don't know how to do it via pyam, because it automatically loads the credientials stored with ixmp4. Any suggestions on how to achieve a guest login? Thanks in advance

**Comment by danielhuppmann** [comment]
You can run `ixmp4 logout` in a console to delete the credentials from your machine, see [here](https://docs.ece.iiasa.ac.at/projects/ixmp4/en/latest/devs/ixmp4.cli.html)

**Comment by lindnemi** [comment]
great, thanks for the quick reply
