### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by lolow** [IAMconsortium/pyam#885]
Hi I have a systematic error when trying to connect to the iiasa server, using `pyam.iiasa.Connection` with credentials, or with `ixmp4 login` in the command line:

```
httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.manager.ece.iiasa.ac.at'. (_ssl.c:1007)
```

Any help to solve this issue is welcome. Thanks.

**Comment by danielhuppmann** [comment]
We believe that IIASA ICT changed the SSL certificates by mistake, we notified them and hoping that this will be fixed asap.

**Comment by korsbakken** [comment]
It's not just pyam. E.g., the online AR6 scenario explorer at https://data.ece.iiasa.ac.at/ar6/ is also unresponsive. So it's apparently a general server issue, not pyam-related.
